"""Strategy Builder Agent — auto-generates strategy code from research recommendations.

Picks up `implement_strategy` and `deferred_implementation` entries from the
knowledge base and generates complete, working strategy files following the
existing codebase patterns. Each generated strategy:

  1. Extends Strategy base class with @register decorator
  2. Implements generate_signals() and get_market_context()
  3. Uses existing data APIs (get_ohlc, get_aster_ohlcv)
  4. Uses existing indicators (ema, sma, rsi, bollinger_bands, z_score, atr)
  5. Follows the signal strength / reason / data contract
  6. Gets auto-registered via registry.py auto-discover

The builder runs as part of the autonomous cycle and is rate-limited to
avoid generating too many strategies at once.
"""

import json
import logging
import os
import re
import textwrap
from datetime import datetime, timezone
from pathlib import Path

from trading.config import STRATEGY_ENABLED
from trading.db.store import (
    get_knowledge, search_knowledge, insert_knowledge, log_action,
    insert_recommendation, resolve_recommendation,
)
from trading.strategy.registry import list_registered

log = logging.getLogger(__name__)

STRATEGY_DIR = Path(__file__).resolve().parent.parent / "strategy"

# Max strategies to build per autonomous cycle
MAX_BUILD_PER_CYCLE = 1

# ---------------------------------------------------------------------------
# Strategy templates — maps category to code generation logic
# ---------------------------------------------------------------------------

# Common header for all generated strategies
_HEADER = '''\
"""{description}

Auto-generated by the Strategy Builder Agent on {date}.
Category: {category} | Priority: {priority}/10 | Expected Sharpe: {sharpe_range}
"""

import logging

import numpy as np
import pandas as pd

from trading.config import CRYPTO_SYMBOLS
from trading.data.crypto import get_ohlc
from trading.strategy.base import Signal, Strategy
from trading.strategy.indicators import {indicators}
from trading.strategy.registry import register

log = logging.getLogger(__name__)

'''

# Template strategies by category
TEMPLATES = {
    "trend_following": {
        "indicators": "ema, sma, atr",
        "generate_body": textwrap.dedent('''\
            signals: list[Signal] = []
            context_data: dict = {}

            for coin_id in self.coins:
                try:
                    alpaca_symbol = CRYPTO_SYMBOLS.get(coin_id)
                    if not alpaca_symbol:
                        continue

                    ohlc = get_ohlc(coin_id, self.lookback_days)
                    if ohlc.empty or len(ohlc) < self.min_data_points:
                        signals.append(Signal(
                            strategy=self.name, symbol=alpaca_symbol, action="hold",
                            strength=0.0, reason=f"{{coin_id}} insufficient data",
                        ))
                        continue

                    close = ohlc["close"]
                    high = ohlc["high"]
                    low = ohlc["low"]

                    fast_ma = ema(close, self.fast_period)
                    slow_ma = ema(close, self.slow_period)
                    current_atr = atr(high, low, close, 14).iloc[-1]

                    # Trend direction
                    trend_up = fast_ma.iloc[-1] > slow_ma.iloc[-1]
                    trend_down = fast_ma.iloc[-1] < slow_ma.iloc[-1]

                    # Crossover detection
                    prev_fast_above = fast_ma.iloc[-2] > slow_ma.iloc[-2]
                    curr_fast_above = fast_ma.iloc[-1] > slow_ma.iloc[-1]

                    cross_up = not prev_fast_above and curr_fast_above
                    cross_down = prev_fast_above and not curr_fast_above

                    # MA separation as strength
                    price = float(close.iloc[-1])
                    separation = abs(fast_ma.iloc[-1] - slow_ma.iloc[-1]) / price
                    strength = min(separation * 20, 1.0)  # Normalize

                    if cross_up or (trend_up and strength > 0.3):
                        action = "buy"
                        reason = f"{{coin_id}} bullish: fast MA crossed above slow, separation {{separation:.1%}}"
                    elif cross_down or (trend_down and strength > 0.3):
                        action = "sell"
                        reason = f"{{coin_id}} bearish: fast MA crossed below slow, separation {{separation:.1%}}"
                    else:
                        action = "hold"
                        reason = f"{{coin_id}} no clear trend signal, separation {{separation:.1%}}"
                        strength = 0.0

                    context_data[coin_id] = {{
                        "price": round(price, 2),
                        "fast_ma": round(float(fast_ma.iloc[-1]), 2),
                        "slow_ma": round(float(slow_ma.iloc[-1]), 2),
                        "atr": round(float(current_atr), 2),
                        "action": action,
                    }}

                    signals.append(Signal(
                        strategy=self.name, symbol=alpaca_symbol, action=action,
                        strength=round(max(strength, 0.0), 4), reason=reason,
                        data={{"coin": coin_id, "separation": round(separation, 4)}},
                    ))
                except Exception as e:
                    sym = CRYPTO_SYMBOLS.get(coin_id, "BTC/USD")
                    log.warning("%s error for %s: %s", self.name, coin_id, e)
                    signals.append(Signal(
                        strategy=self.name, symbol=sym, action="hold",
                        strength=0.0, reason=f"{{coin_id}} error: {{e}}",
                    ))

            self._last_context = context_data
            return signals
        '''),
        "config_params": {
            "coins": '["bitcoin", "ethereum", "solana"]',
            "lookback_days": "120",
            "fast_period": "12",
            "slow_period": "26",
            "min_data_points": "30",
        },
    },
    "mean_reversion": {
        "indicators": "bollinger_bands, z_score, rsi",
        "generate_body": textwrap.dedent('''\
            signals: list[Signal] = []
            context_data: dict = {}

            for coin_id in self.coins:
                try:
                    alpaca_symbol = CRYPTO_SYMBOLS.get(coin_id)
                    if not alpaca_symbol:
                        continue

                    ohlc = get_ohlc(coin_id, self.lookback_days)
                    if ohlc.empty or len(ohlc) < self.min_data_points:
                        signals.append(Signal(
                            strategy=self.name, symbol=alpaca_symbol, action="hold",
                            strength=0.0, reason=f"{{coin_id}} insufficient data",
                        ))
                        continue

                    close = ohlc["close"]
                    current_rsi = rsi(close, 14).iloc[-1]
                    upper, mid, lower = bollinger_bands(close, self.bb_period, self.bb_std)
                    price = float(close.iloc[-1])

                    # Z-score of price relative to rolling mean
                    zs = z_score(close, self.bb_period).iloc[-1]

                    # Mean reversion signals
                    if price <= float(lower.iloc[-1]) and current_rsi < self.rsi_oversold:
                        action = "buy"
                        strength = min(abs(zs) / 3.0, 1.0)
                        reason = f"{{coin_id}} oversold: RSI={{current_rsi:.0f}}, z={{zs:.2f}}, at lower BB"
                    elif price >= float(upper.iloc[-1]) and current_rsi > self.rsi_overbought:
                        action = "sell"
                        strength = min(abs(zs) / 3.0, 1.0)
                        reason = f"{{coin_id}} overbought: RSI={{current_rsi:.0f}}, z={{zs:.2f}}, at upper BB"
                    else:
                        action = "hold"
                        strength = 0.0
                        reason = f"{{coin_id}} no mean reversion signal, z={{zs:.2f}}, RSI={{current_rsi:.0f}}"

                    context_data[coin_id] = {{
                        "price": round(price, 2),
                        "rsi": round(float(current_rsi), 1),
                        "z_score": round(float(zs), 2),
                        "upper_bb": round(float(upper.iloc[-1]), 2),
                        "lower_bb": round(float(lower.iloc[-1]), 2),
                        "action": action,
                    }}

                    signals.append(Signal(
                        strategy=self.name, symbol=alpaca_symbol, action=action,
                        strength=round(max(strength, 0.0), 4), reason=reason,
                        data={{"coin": coin_id, "z_score": round(float(zs), 2), "rsi": round(float(current_rsi), 1)}},
                    ))
                except Exception as e:
                    sym = CRYPTO_SYMBOLS.get(coin_id, "BTC/USD")
                    log.warning("%s error for %s: %s", self.name, coin_id, e)
                    signals.append(Signal(
                        strategy=self.name, symbol=sym, action="hold",
                        strength=0.0, reason=f"{{coin_id}} error: {{e}}",
                    ))

            self._last_context = context_data
            return signals
        '''),
        "config_params": {
            "coins": '["bitcoin", "ethereum", "solana"]',
            "lookback_days": "120",
            "bb_period": "20",
            "bb_std": "2.0",
            "rsi_oversold": "30",
            "rsi_overbought": "70",
            "min_data_points": "30",
        },
    },
    "momentum": {
        "indicators": "rsi, ema, atr",
        "generate_body": textwrap.dedent('''\
            signals: list[Signal] = []
            context_data: dict = {}

            for coin_id in self.coins:
                try:
                    alpaca_symbol = CRYPTO_SYMBOLS.get(coin_id)
                    if not alpaca_symbol:
                        continue

                    ohlc = get_ohlc(coin_id, self.lookback_days)
                    if ohlc.empty or len(ohlc) < self.min_data_points:
                        signals.append(Signal(
                            strategy=self.name, symbol=alpaca_symbol, action="hold",
                            strength=0.0, reason=f"{{coin_id}} insufficient data",
                        ))
                        continue

                    close = ohlc["close"]
                    high = ohlc["high"]
                    low = ohlc["low"]

                    # Rate of change (momentum)
                    roc = (close.iloc[-1] - close.iloc[-self.momentum_period]) / close.iloc[-self.momentum_period]
                    current_rsi = rsi(close, 14).iloc[-1]
                    trend_ema = ema(close, self.trend_period)
                    current_atr = atr(high, low, close, 14).iloc[-1]
                    price = float(close.iloc[-1])

                    # Momentum signals: strong ROC + trend confirmation
                    above_trend = price > float(trend_ema.iloc[-1])

                    if roc > self.roc_threshold and above_trend and current_rsi > 50:
                        action = "buy"
                        strength = min(roc / (self.roc_threshold * 3), 1.0)
                        reason = f"{{coin_id}} momentum buy: ROC={{roc:.1%}}, RSI={{current_rsi:.0f}}, above trend"
                    elif roc < -self.roc_threshold and not above_trend and current_rsi < 50:
                        action = "sell"
                        strength = min(abs(roc) / (self.roc_threshold * 3), 1.0)
                        reason = f"{{coin_id}} momentum sell: ROC={{roc:.1%}}, RSI={{current_rsi:.0f}}, below trend"
                    else:
                        action = "hold"
                        strength = 0.0
                        reason = f"{{coin_id}} no momentum signal, ROC={{roc:.1%}}"

                    context_data[coin_id] = {{
                        "price": round(price, 2),
                        "roc": round(float(roc), 4),
                        "rsi": round(float(current_rsi), 1),
                        "trend_ema": round(float(trend_ema.iloc[-1]), 2),
                        "action": action,
                    }}

                    signals.append(Signal(
                        strategy=self.name, symbol=alpaca_symbol, action=action,
                        strength=round(max(strength, 0.0), 4), reason=reason,
                        data={{"coin": coin_id, "roc": round(float(roc), 4)}},
                    ))
                except Exception as e:
                    sym = CRYPTO_SYMBOLS.get(coin_id, "BTC/USD")
                    log.warning("%s error for %s: %s", self.name, coin_id, e)
                    signals.append(Signal(
                        strategy=self.name, symbol=sym, action="hold",
                        strength=0.0, reason=f"{{coin_id}} error: {{e}}",
                    ))

            self._last_context = context_data
            return signals
        '''),
        "config_params": {
            "coins": '["bitcoin", "ethereum", "solana"]',
            "lookback_days": "120",
            "momentum_period": "20",
            "roc_threshold": "0.05",
            "trend_period": "50",
            "min_data_points": "50",
        },
    },
}

# Fallback: use momentum template for unknown categories
_DEFAULT_CATEGORY = "momentum"


# ---------------------------------------------------------------------------
# Code generation
# ---------------------------------------------------------------------------

def _snake_case(name: str) -> str:
    """Convert a strategy name to snake_case for filenames and class names."""
    # Replace special chars with underscore
    s = re.sub(r'[^a-zA-Z0-9]', '_', name)
    # CamelCase to snake
    s = re.sub(r'([A-Z])', r'_\1', s).lower()
    # Collapse multiple underscores
    s = re.sub(r'_+', '_', s).strip('_')
    return s


def _class_name(snake: str) -> str:
    """Convert snake_case to CamelCase class name."""
    return ''.join(word.capitalize() for word in snake.split('_')) + 'Strategy'


def _map_category(category: str) -> str:
    """Map strategy universe category to template category."""
    category_lower = category.lower()
    if any(k in category_lower for k in ["trend", "breakout", "channel"]):
        return "trend_following"
    elif any(k in category_lower for k in ["mean_reversion", "reversion", "contrarian", "stat_arb"]):
        return "mean_reversion"
    elif any(k in category_lower for k in ["momentum", "relative_strength", "rotation"]):
        return "momentum"
    # Default
    return _DEFAULT_CATEGORY


def generate_strategy_code(
    strategy_name: str,
    description: str,
    category: str,
    priority: int = 5,
    sharpe_range: str = "0.3-1.0",
    complexity: str = "low",
    data_needed: str = "OHLCV",
) -> str:
    """Generate a complete strategy module from a spec."""
    snake = _snake_case(strategy_name)
    cls_name = _class_name(snake)
    template_cat = _map_category(category)
    template = TEMPLATES.get(template_cat, TEMPLATES[_DEFAULT_CATEGORY])

    config_name = snake.upper()
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Build config dict
    config_lines = [f'{config_name} = {{']
    for key, default_val in template["config_params"].items():
        config_lines.append(f'    "{key}": {default_val},')
    config_lines.append('}')
    config_str = '\n'.join(config_lines)

    # Build __init__ body
    init_lines = [f'        cfg = {config_name}']
    for key in template["config_params"]:
        init_lines.append(f'        self.{key} = cfg["{key}"]')
    init_lines.append('        self._last_context: dict = {}')
    init_str = '\n'.join(init_lines)

    # Header
    header = _HEADER.format(
        description=description,
        date=date,
        category=category,
        priority=priority,
        sharpe_range=sharpe_range,
        indicators=template["indicators"],
    )

    # Indent the generate body
    gen_body = template["generate_body"]
    # Indent by 8 spaces (inside a method)
    gen_lines = []
    for line in gen_body.splitlines():
        if line.strip():
            gen_lines.append('        ' + line)
        else:
            gen_lines.append('')
    gen_body_indented = '\n'.join(gen_lines)

    code = f'''{header}
{config_str}


@register
class {cls_name}(Strategy):
    """{description}"""

    name = "{snake}"

    def __init__(self):
{init_str}

    def generate_signals(self) -> list[Signal]:
{gen_body_indented}

    def get_market_context(self) -> dict:
        return {{"strategy": self.name, "coins": self._last_context}}
'''
    return code


# ---------------------------------------------------------------------------
# Builder agent — called from autonomous cycle
# ---------------------------------------------------------------------------

def _get_deferred_implementations() -> list[dict]:
    """Get strategy implementation requests from the knowledge base."""
    results = search_knowledge("deferred_implementation", limit=20)
    deferred = []
    for r in results:
        if r.get("category") == "deferred_implementation":
            try:
                data = json.loads(r.get("key_rules", "{}"))
            except (json.JSONDecodeError, TypeError):
                data = {}
            deferred.append({
                "id": r.get("id"),
                "title": r.get("title", ""),
                "content": r.get("content", ""),
                "data": data,
                "timestamp": r.get("ingested_at", ""),
            })
    return deferred


def _already_implemented(strategy_name: str) -> bool:
    """Check if a strategy is already registered."""
    snake = _snake_case(strategy_name)
    registered = list_registered()
    return snake in registered


def build_pending_strategies() -> list[dict]:
    """Build strategies from deferred implementation requests.

    Called from the autonomous cycle. Rate-limited to MAX_BUILD_PER_CYCLE
    strategies per invocation.

    Returns list of {"name": str, "file": str, "result": str} for each built.
    """
    built = []
    deferred = _get_deferred_implementations()

    if not deferred:
        return built

    for entry in deferred[:MAX_BUILD_PER_CYCLE]:
        data = entry.get("data", {})
        name = data.get("name", "")
        if not name:
            # Try to extract from title
            title = entry.get("title", "")
            match = re.search(r"Request:\s*(.+?)\s*—", title)
            name = match.group(1) if match else ""
        if not name:
            continue

        snake = _snake_case(name)

        # Skip if already implemented
        if _already_implemented(name):
            log.info("BUILDER: Strategy '%s' already implemented, skipping", name)
            continue

        # Skip if file already exists
        file_path = STRATEGY_DIR / f"{snake}.py"
        if file_path.exists():
            log.info("BUILDER: File %s already exists, skipping", file_path.name)
            continue

        category = data.get("category", "momentum")
        priority = data.get("priority", 5)
        sharpe_range = data.get("sharpe_range", "0.3-1.0")
        complexity = data.get("complexity", "low")
        data_needed = data.get("data_needed", "OHLCV")
        description = entry.get("content", f"{name} strategy")

        try:
            code = generate_strategy_code(
                strategy_name=name,
                description=description[:200],  # Keep docstring reasonable
                category=category,
                priority=priority,
                sharpe_range=sharpe_range,
                complexity=complexity,
                data_needed=data_needed,
            )

            # Write the strategy file
            file_path.write_text(code)

            # Register in STRATEGY_ENABLED (disabled by default — backtest first)
            STRATEGY_ENABLED[snake] = False

            # Log the build
            log_action(
                "strategy_builder", "strategy_generated",
                symbol=snake,
                details=f"Generated {snake}.py from research recommendation (priority {priority}/10, {category})",
                data={
                    "name": name,
                    "snake_name": snake,
                    "category": category,
                    "priority": priority,
                    "sharpe_range": sharpe_range,
                    "file": str(file_path),
                },
            )

            # Update knowledge base
            insert_knowledge(
                title=f"Strategy Built: {name} — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}",
                source="strategy_builder",
                category="strategy_built",
                content=f"Auto-generated {snake}.py from research recommendation. "
                        f"Category: {category}, Priority: {priority}/10. "
                        f"Strategy is DISABLED — awaiting backtest validation.",
                key_rules=json.dumps({"snake_name": snake, "category": category}),
            )

            built.append({
                "name": name,
                "snake_name": snake,
                "file": str(file_path),
                "result": "generated_disabled",
            })

            log.info("STRATEGY BUILDER: Generated %s.py (category=%s, priority=%d) — disabled, awaiting backtest",
                     snake, category, priority)

        except Exception as e:
            log.error("STRATEGY BUILDER: Failed to generate %s: %s", name, e, exc_info=True)
            log_action(
                "strategy_builder", "generation_failed",
                symbol=snake,
                details=f"Failed to generate {name}: {e}",
            )

    return built
