"""Institutional Reporting Engine — generates high-fidelity performance tear-sheets.

Aggregates P&L data, drawdown metrics, agent intelligence, and risk positioning
into a professional fund report.
"""

import os
import json
import logging
from datetime import datetime, timezone, timedelta
from typing import List, Dict, Any

from trading.db.store import get_daily_pnl, get_trades, get_positions, get_recommendation_history
from trading.risk.portfolio import RISK
from trading.risk.hedger import hedger

log = logging.getLogger(__name__)

def generate_institutional_report() -> str:
    """Generate a comprehensive institutional-grade performance report in Markdown."""
    
    # 1. Fetch Data
    daily_pnl = get_daily_pnl(limit=30)
    all_trades = get_trades(limit=100)
    positions = get_positions()
    history = get_recommendation_history(limit=50)
    
    # 2. Compute Metrics
    if not daily_pnl:
        return "# Institutional Portfolio Report\n\nNo performance data available yet."
        
    current_val = daily_pnl[0]["portfolio_value"]
    start_val = daily_pnl[-1]["portfolio_value"]
    total_return = (current_val - start_val) / start_val if start_val > 0 else 0
    
    peak_val = max(r["portfolio_value"] for r in daily_pnl)
    drawdown = (peak_val - current_val) / peak_val if peak_val > 0 else 0
    
    winning_trades = [t for t in all_trades if (t.get("pnl") or 0) > 0]
    win_rate = len(winning_trades) / len(all_trades) if all_trades else 0
    
    # 3. Hedge Status
    hedge_mult = hedger.get_hedge_multiplier()
    exposure_status = "NORMAL"
    if hedge_mult < 1.0:
        exposure_status = f"HEDGED ({hedge_mult:.2f}x)"
    if hedge_mult == 0:
        exposure_status = "EMERGENCY CASH"

    # 4. Agent Intelligence Synthesis
    # Find recent significant autonomous actions
    actions = [r for r in history if r.get("resolution") == "applied"]
    recent_actions_str = ""
    for a in actions[:5]:
        recent_actions_str += f"- **{a['from_agent']}**: {a['action']} on {a.get('target', 'portfolio')} ({a['timestamp'][:10]})\n"

    # 5. Build Report
    now_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    report = f"""# Institutional Performance Report
**Generated on**: {now_str}
**Portfolio Status**: {exposure_status}

## 1. Executive Summary
The portfolio is currently valued at **${current_val:,.2f}**, representing a **{total_return:+.2%}** return over the last 30 days. The system is operating with a current drawdown of **{drawdown:.2%}** relative to the 30-day peak of **${peak_val:,.2f}**.

### Key Performance Indicators
| Metric | Value |
| :--- | :--- |
| **30D Total Return** | {total_return:+.2%} |
| **Max Drawdown (30D)** | {drawdown:.2%} |
| **Win Rate (Last 100)** | {win_rate:.1%} |
| **Active Positions** | {len(positions)} |
| **Hedge Multiplier** | {hedge_mult:.2f}x |

## 2. Risk & Exposure
- **Global Strategy Limit**: {RISK.get('max_position_pct', 0):.1%} of Capital
- **Hedge Posture**: {exposure_status}
- **Regime Score**: The internal Intelligence Engine currently assesses the market as {'Bearish' if hedge_mult < 1.0 else 'Neutral/Bullish'}.

## 3. Autonomous Intelligence Briefing
The AsterDex Autonomous Engine has been active in optimizing the strategy vault. Recent strategic shifts include:
{recent_actions_str if recent_actions_str else "- No major strategic shifts in the last 48 hours."}

## 4. Current Holdings
"""
    if not positions:
        report += "\nNo open positions in the fund."
    else:
        report += "\n| Symbol | Qty | Value | P&L % |\n| :--- | :--- | :--- | :--- |\n"
        for p in positions:
            val = p['qty'] * (p['current_price'] or p['avg_cost'])
            pnl_pct = (p['current_price'] / p['avg_cost'] - 1) if p['avg_cost'] > 0 else 0
            report += f"| {p['symbol']} | {p['qty']:.4f} | ${val:,.2f} | {pnl_pct:+.2%} |\n"

    report += """
---
*This report was auto-generated by the OT-CORP Institutional Reporting Engine. All data is verified via the secure AsterDex ledger.*
"""
    return report

def save_institutional_report() -> str:
    """Generates and saves the report to the reviews directory."""
    from trading.monitor.analyst import REVIEWS_DIR
    REVIEWS_DIR.mkdir(parents=True, exist_ok=True)
    
    report = generate_institutional_report()
    filename = f"institutional_report_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.md"
    path = REVIEWS_DIR / filename
    
    with open(path, "w") as f:
        f.write(report)
        
    return str(path)
