"""Strategy 'Dual Momentum (Antonacci)' (Momentum) has priority 8/10, expected Sharpe 0.6-1.3, complexity: medium. Data needed: OHLCV multi-asset. This is a high-value implementation target.

Auto-generated by the Strategy Builder Agent on 2026-03-17.
Category: Momentum | Priority: 8/10 | Expected Sharpe: 0.6-1.3
"""

import logging

import numpy as np
import pandas as pd

from trading.config import BYBIT_SYMBOLS
from trading.data.crypto import get_ohlc
from trading.strategy.base import Signal, Strategy
from trading.strategy.indicators import rsi, ema, atr
from trading.strategy.registry import register

log = logging.getLogger(__name__)


DUAL_MOMENTUM_ANTONACCI = {
    "coins": ["bitcoin", "ethereum", "solana"],
    "lookback_days": 120,
    "momentum_period": 20,
    "roc_threshold": 0.05,
    "trend_period": 50,
    "min_data_points": 50,
}


@register
class DualMomentumAntonacciStrategy(Strategy):
    """Strategy 'Dual Momentum (Antonacci)' (Momentum) has priority 8/10, expected Sharpe 0.6-1.3, complexity: medium. Data needed: OHLCV multi-asset. This is a high-value implementation target."""

    name = "dual_momentum_antonacci"

    def __init__(self):
        cfg = DUAL_MOMENTUM_ANTONACCI
        self.coins = cfg["coins"]
        self.lookback_days = cfg["lookback_days"]
        self.momentum_period = cfg["momentum_period"]
        self.roc_threshold = cfg["roc_threshold"]
        self.trend_period = cfg["trend_period"]
        self.min_data_points = cfg["min_data_points"]
        self._last_context: dict = {}

    def generate_signals(self) -> list[Signal]:
        signals: list[Signal] = []
        context_data: dict = {}

        for coin_id in self.coins:
            try:
                bybit_symbol = BYBIT_SYMBOLS.get(coin_id)
                if not bybit_symbol:
                    continue

                ohlc = get_ohlc(coin_id, self.lookback_days)
                if ohlc.empty or len(ohlc) < self.min_data_points:
                    signals.append(Signal(
                        strategy=self.name, symbol=bybit_symbol, action="hold",
                        strength=0.0, reason=f"{{coin_id}} insufficient data",
                    ))
                    continue

                close = ohlc["close"]
                high = ohlc["high"]
                low = ohlc["low"]

                # Rate of change (momentum)
                roc = (close.iloc[-1] - close.iloc[-self.momentum_period]) / close.iloc[-self.momentum_period]
                current_rsi = rsi(close, 14).iloc[-1]
                trend_ema = ema(close, self.trend_period)
                current_atr = atr(high, low, close, 14).iloc[-1]
                price = float(close.iloc[-1])

                # Momentum signals: strong ROC + trend confirmation
                above_trend = price > float(trend_ema.iloc[-1])

                if roc > self.roc_threshold and above_trend and current_rsi > 50:
                    action = "buy"
                    strength = min(roc / (self.roc_threshold * 3), 1.0)
                    reason = f"{{coin_id}} momentum buy: ROC={{roc:.1%}}, RSI={{current_rsi:.0f}}, above trend"
                elif roc < -self.roc_threshold and not above_trend and current_rsi < 50:
                    action = "sell"
                    strength = min(abs(roc) / (self.roc_threshold * 3), 1.0)
                    reason = f"{{coin_id}} momentum sell: ROC={{roc:.1%}}, RSI={{current_rsi:.0f}}, below trend"
                else:
                    action = "hold"
                    strength = 0.0
                    reason = f"{{coin_id}} no momentum signal, ROC={{roc:.1%}}"

                context_data[coin_id] = {{
                    "price": round(price, 2),
                    "roc": round(float(roc), 4),
                    "rsi": round(float(current_rsi), 1),
                    "trend_ema": round(float(trend_ema.iloc[-1]), 2),
                    "action": action,
                }}

                signals.append(Signal(
                    strategy=self.name, symbol=bybit_symbol, action=action,
                    strength=round(max(strength, 0.0), 4), reason=reason,
                    data={{"coin": coin_id, "roc": round(float(roc), 4)}},
                ))
            except Exception as e:
                sym = BYBIT_SYMBOLS.get(coin_id, "BTC/USD")
                log.warning("%s error for %s: %s", self.name, coin_id, e)
                signals.append(Signal(
                    strategy=self.name, symbol=sym, action="hold",
                    strength=0.0, reason=f"{{coin_id}} error: {{e}}",
                ))

        self._last_context = context_data
        return signals

    def get_market_context(self) -> dict:
        return {"strategy": self.name, "coins": self._last_context}
