"""Autonomous trading scheduler v3.0 — runs strategies on autopilot.

Integrates:
  - Structured logging (Python logging module)
  - Signal aggregation (deduplicate, resolve conflicts)
  - Market hours gating (ETFs only during NYSE hours)
  - Position sync (Alpaca -> local DB)
  - Fill verification (poll pending orders)
  - Trade pairing (FIFO buy-sell matching for P&L)
  - Take-profit + trailing stop
  - Notifications (Discord / Telegram)
  - Correlation limits + crypto exposure cap
  - Volatility-adjusted position sizing (ATR)
  - Per-strategy risk budgets
  - Order retry with exponential backoff
  - Approved adaptation application
  - Account safety checks (trading_blocked, buying_power)
  - Proper daily P&L calculation (prev-day comparison)
"""

import logging
import os
import signal as signal_mod
import time
import traceback
from datetime import datetime, timedelta, timezone

import schedule
from rich.console import Console

from trading.config import TRADING_MODE, RISK, INITIAL_CAPITAL
from trading.db.store import (
    init_db, get_db, insert_trade, insert_signal, log_action,
    normalize_symbol, record_daily_pnl, get_action_log, get_daily_pnl,
    get_setting, set_setting,
)

log = logging.getLogger(__name__)
console = Console()


# ---------------------------------------------------------------------------
# Pre-trade narration — human-readable story of why a trade is happening
# ---------------------------------------------------------------------------

def _narrate_trade(signal, order_value, portfolio_value, risk_check, context, stop_loss_price=None):
    """Build a human-readable pre-trade narration in natural prose.

    Combines signal data, market context, risk parameters, and position sizing
    into a narrative that explains *why* this trade is being taken.
    """
    sym = signal.symbol
    action = signal.action.upper()
    strength = signal.strength
    pct_of_portfolio = (order_value / portfolio_value * 100) if portfolio_value > 0 else 0

    # Opening sentence
    parts = [
        f"Opening a {action.lower()} position in {sym} for ${order_value:.2f}, "
        f"representing {pct_of_portfolio:.1f}% of the portfolio."
    ]

    # Signal source
    contributing = (signal.data or {}).get("contributing_strategies", [])
    if contributing:
        strat_list = ", ".join(contributing[:4])
        if len(contributing) > 4:
            strat_list += f" and {len(contributing) - 4} more"
        parts.append(
            f"This trade is backed by consensus from {len(contributing)} strategies "
            f"({strat_list}) with a combined signal strength of {strength:.2f}."
        )
    else:
        parts.append(
            f"Signal generated by {signal.strategy} with strength {strength:.2f}."
        )

    # Signal rationale
    if signal.reason:
        # Clean up strategy-internal reasons for readability
        reason = signal.reason
        if len(reason) < 200:
            parts.append(f"{reason}.")

    # Risk & stops
    risk_parts = []
    if stop_loss_price and stop_loss_price > 0:
        risk_parts.append(f"stop loss at ${stop_loss_price:.2f}")
    if risk_check and hasattr(risk_check, 'reason') and risk_check.reason:
        risk_parts.append(risk_check.reason.lower())
    if risk_parts:
        parts.append(f"Risk management: {'; '.join(risk_parts)}.")

    return "\n\n".join(parts)


# ---------------------------------------------------------------------------
# Persistent tracker -- created once, lives for the daemon's lifetime
# ---------------------------------------------------------------------------
_profit_tracker = None  # Lazy init in start_daemon


def _get_profit_tracker():
    global _profit_tracker
    if _profit_tracker is None:
        from trading.risk.profit_manager import ProfitTracker
        _profit_tracker = ProfitTracker()
    return _profit_tracker


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _now_str():
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def _get_account():
    """Get account from AsterDex (primary execution venue)."""
    from trading.execution.router import get_account
    return get_account()


def _get_positions():
    """Get positions from AsterDex."""
    from trading.execution.router import get_positions_from_aster
    return get_positions_from_aster()


def _execute_order(symbol, side, notional=None, qty=None, stop_loss_price=None, leverage=1):
    """Execute order via AsterDex perpetual futures."""
    if leverage > 1:
        try:
            from trading.execution.aster_client import aster_set_leverage
            aster_set_leverage(symbol, leverage)
        except Exception as e:
            log.warning("Failed to set leverage %dx for %s: %s", leverage, symbol, e)
    from trading.execution.router import submit_order
    return submit_order(symbol, side, notional=notional, qty=qty,
                        stop_loss_price=stop_loss_price, leverage=leverage)


def _notify_safe(func, *args, **kwargs):
    """Call a notification function, swallowing any exception."""
    try:
        func(*args, **kwargs)
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Core trading cycle -- with aggregation + market hours gating
# ---------------------------------------------------------------------------

def run_trading_cycle():
    """One complete cycle: data -> signals -> aggregate -> risk -> execute -> sync."""
    from trading.strategy.registry import get_enabled_strategies
    from trading.strategy.aggregator import aggregate_signals
    from trading.risk.manager import RiskManager
    from trading.risk.portfolio import calculate_order_size
    from trading.learning.journal import create_journal_entry
    from trading.execution.market_hours import can_trade_now
    from trading.execution.sync import run_sync
    from trading.data.cache import clear_cache
    from trading.risk.portfolio import clear_allocation_cache
    from trading.monitor.notifications import notify_trade, notify_error, notify_cycle_summary

    clear_cache()  # Fresh data each cycle
    clear_allocation_cache()  # Reset dynamic sizing caches (confluence, regime, perf)

    # Sync trading mode from DB (may have been changed via dashboard toggle)
    # Store in a cycle-local variable — don't mutate the config module directly
    from trading.db.store import get_setting
    import trading.config as _cfg
    db_mode = get_setting("trading_mode")
    if db_mode:
        _cycle_trading_mode = db_mode
        if db_mode != _cfg.TRADING_MODE:
            log.info("Trading mode for this cycle: %s (config default: %s)", db_mode, _cfg.TRADING_MODE)
    else:
        _cycle_trading_mode = _cfg.TRADING_MODE

    # Restore autonomous state FIRST so emergency halts persist across cycles
    from trading.intelligence.autonomous import load_persisted_state
    load_persisted_state()

    # Apply operator overrides (can layer on top of autonomous state)
    from trading.monitor.operator_hooks import apply_strategy_overrides, apply_risk_overrides
    apply_strategy_overrides()
    apply_risk_overrides()

    log_action("strategy_run", "cycle_start", details=f"Mode: {_cfg.TRADING_MODE}")
    log.info("Trading cycle started")
    _cycle_start_time = time.monotonic()
    console.print(f"\n[bold cyan]{'='*60}[/]")
    console.print(f"[bold]Trading cycle started -- {_now_str()}[/bold]")
    console.print(f"[bold cyan]{'='*60}[/]")

    try:
        account = _get_account()
        portfolio_value = account["portfolio_value"]
        mode = "PAPER" if account.get("paper") else "LIVE"
        console.print(f"[dim]Portfolio: ${portfolio_value:.2f} ({mode})[/dim]")

        # ---------------------------------------------------------------
        # Phase 0: Account safety checks
        # ---------------------------------------------------------------
        if account.get("trading_blocked"):
            msg = "Trading blocked by broker -- aborting cycle"
            log.error(msg)
            console.print(f"[bold red]{msg}[/bold red]")
            log_action("error", "trading_blocked", details=msg)
            _notify_safe(notify_error, msg, "account_check")
            return

        # ---------------------------------------------------------------
        # Phase 0.1: Strategy deployment pre-flight
        # ---------------------------------------------------------------
        from trading.strategy.registry import preflight_check
        from trading.monitor.notifications import notify_deployment_failure
        pf = preflight_check()
        if not pf.passed:
            msg = f"STRATEGY PREFLIGHT FAILED: {len(pf.missing)} missing, {len(pf.failed)} broken"
            details = []
            for name in pf.missing:
                details.append(f"  MISSING: {name} — no module found")
            for name, err in pf.failed.items():
                details.append(f"  BROKEN: {name} — {err}")
            detail_str = "\n".join(details)
            log.error("%s\n%s", msg, detail_str)
            console.print(f"[bold red]{msg}[/bold red]")
            for line in details:
                console.print(f"[red]{line}[/red]")
            log_action("error", "preflight_failed", details=f"{msg}\n{detail_str}",
                       data={"missing": pf.missing, "failed": pf.failed, "escalation": 1})
            _notify_safe(notify_deployment_failure, pf.missing, pf.failed)
            # Continue in degraded mode with whatever strategies loaded
        else:
            console.print(f"[green]Pre-flight: {len(pf.loaded)} strategies loaded OK[/green]")

        # ---------------------------------------------------------------
        # Phase 0.5: Apply approved parameter adaptations
        # ---------------------------------------------------------------
        try:
            from trading.learning.adaptor import apply_approved
            applied = apply_approved()
            if applied:
                for a in applied:
                    console.print(f"  [magenta]ADAPTED {a['strategy']}.{a['param']}: {a['old']} -> {a['new']}[/]")
                log_action("system", "adaptations_applied", details=f"{len(applied)} params updated")
        except Exception as e:
            log.warning("Adaptation application failed: %s", e)

        # ---------------------------------------------------------------
        # Phase 1: Sync positions from broker -> local DB (fixes risk checks)
        # CRITICAL: If position sync fails, halt trading — risk checks
        # depend on accurate position data.
        # ---------------------------------------------------------------
        try:
            sync_result = run_sync()
            console.print(f"[dim]Sync: {sync_result}[/dim]")
        except Exception as e:
            from trading.execution.sync import SyncError
            if isinstance(e, SyncError):
                msg = f"HALTING CYCLE: Position sync failed — {e}"
                log.error(msg)
                console.print(f"[bold red]{msg}[/bold red]")
                log_action("error", "sync_halt", details=msg)
                _notify_safe(notify_error, msg, "position_sync")
                return
            # Non-sync errors (fill verification, pairing) are warnings
            log.warning("Sync warning: %s", e)
            console.print(f"[yellow]Sync warning: {e}[/yellow]")

        # ---------------------------------------------------------------
        # Phase 1.5: Market Intelligence Briefing
        # ---------------------------------------------------------------
        briefing = None
        try:
            from trading.intelligence.engine import generate_briefing
            briefing = generate_briefing()
            console.print(f"\n[bold gold1]Intelligence:[/] {briefing.summary()}")
            for cat, info in briefing.categories.items():
                score = info['score']
                color = "green" if score > 0.1 else "red" if score < -0.1 else "dim"
                conf = info.get('confidence', 0)
                comps = ", ".join(info.get('components', []))
                console.print(f"  [{color}]{cat}: {score:+.2f} ({info['label']}, {conf:.0%} conf)[/{color}]")
                if comps:
                    console.print(f"    [dim]{comps}[/dim]")
            if briefing.event_risk:
                console.print(f"  [bold red]EVENT RISK: {', '.join(briefing.event_risk)}[/bold red]")
            log_action("intelligence", "briefing", details=briefing.summary(),
                       data=briefing.to_dict())
        except Exception as e:
            log.warning("Intelligence briefing failed (non-fatal): %s", e)
            console.print(f"[yellow]Intelligence briefing skipped: {e}[/yellow]")

        # ---------------------------------------------------------------
        # Phase 2: Collect ALL signals from ALL strategies
        # ---------------------------------------------------------------
        strategies = get_enabled_strategies()
        raw_signals = []
        contexts = {}
        if briefing:
            contexts["_intelligence"] = briefing.to_dict()

        # Determine current market regime for regime-gating
        current_regime = None
        if briefing:
            current_regime = briefing.overall_regime  # "bull", "bear", "sideways", "neutral"
        from trading.config import STRATEGY_REGIME_REQUIREMENTS
        from trading.strategy.circuit_breaker import check_circuit_breaker

        for strategy in strategies:
            # Circuit breaker: skip strategies with consecutive losses
            if check_circuit_breaker(strategy.name):
                console.print(f"\n[red]-> {strategy.name} (CIRCUIT BROKEN — 48h cooldown)[/red]")
                continue

            # Regime-conditional activation: skip strategies in wrong regime
            regime_reqs = STRATEGY_REGIME_REQUIREMENTS.get(strategy.name)
            if regime_reqs and current_regime and current_regime not in regime_reqs:
                console.print(f"\n[dim]-> {strategy.name} (skipped: regime '{current_regime}' not in {regime_reqs})[/dim]")
                log.debug("Skipping %s: regime %s not in %s", strategy.name, current_regime, regime_reqs)
                continue

            console.print(f"\n[cyan]-> {strategy.name}[/cyan]")
            try:
                signals = strategy.generate_signals()
                context = strategy.get_market_context()
                contexts[strategy.name] = context

                for signal in signals:
                    insert_signal(
                        signal.strategy, signal.symbol, signal.action,
                        signal.strength, signal.data,
                    )
                    log_action(
                        "signal", signal.action,
                        symbol=signal.symbol,
                        details=signal.reason,
                        data={"strength": signal.strength, "strategy": signal.strategy},
                    )
                    raw_signals.append(signal)

            except Exception as e:
                log_action("error", "strategy_error", details=f"{strategy.name}: {e}")
                log.error("Strategy %s failed: %s", strategy.name, e)
                console.print(f"  [red]Error: {e}[/red]")
                _notify_safe(notify_error, f"{strategy.name}: {e}", "strategy_generation")

        signal_count = len(raw_signals)

        # ---------------------------------------------------------------
        # Phase 3: Aggregate signals (deduplicate + conflict resolution)
        # ---------------------------------------------------------------
        consolidated = aggregate_signals(raw_signals)
        log.info("Aggregation: %d raw -> %d consolidated", signal_count, len(consolidated))
        console.print(
            f"\n[bold]Aggregation: {signal_count} raw -> "
            f"{len(consolidated)} consolidated[/bold]"
        )

        # ---------------------------------------------------------------
        # Phase 3.5: Replay deferred signals from previous cycles
        # ---------------------------------------------------------------
        try:
            from trading.db.store import get_deferred_signals, clear_deferred_signal
            deferred = get_deferred_signals()
            if deferred:
                from trading.strategy.base import Signal
                for ds in deferred:
                    can_trade_deferred, _ = can_trade_now(ds["symbol"])
                    if can_trade_deferred:
                        replay_signal = Signal(
                            strategy=ds["strategy"],
                            symbol=ds["symbol"],
                            action=ds["action"],
                            strength=ds["strength"],
                            reason=f"Deferred replay: {ds['reason']}",
                        )
                        consolidated.append(replay_signal)
                        clear_deferred_signal(ds["id"])
                        console.print(f"  [green]REPLAYED deferred {ds['symbol']} {ds['action']}[/green]")
                        log_action("signal", "deferred_replay", symbol=ds["symbol"],
                                   details=f"Replayed from {ds['timestamp']}")
                    # Clean up expired signals silently
                # Re-log consolidated count if replays added
                if any(can_trade_now(ds["symbol"])[0] for ds in deferred):
                    log.info("After deferred replay: %d consolidated signals", len(consolidated))
        except Exception as e:
            log.warning("Deferred signal replay failed: %s", e)

        # ---------------------------------------------------------------
        # Phase 4: Risk check + market hours gate + execute
        # ---------------------------------------------------------------
        risk_mgr = RiskManager(portfolio_value, account=account)
        executed_count = 0
        blocked_count = 0

        # Count buy signals for position sizing
        buy_count = sum(1 for s in consolidated if s.action == "buy")

        # Pre-fetch positions to skip sells for symbols we don't hold
        positions_for_gate = _get_positions()
        held_symbols = {p["symbol"] for p in positions_for_gate}

        actionable_count = sum(1 for s in consolidated if s.is_actionable)

        for signal in consolidated:
            if not signal.is_actionable:
                continue

            # Skip sells for symbols we don't hold (unless short-selling is allowed)
            if signal.action == "sell":
                norm = signal.symbol.replace("/", "")
                if norm not in held_symbols and signal.symbol not in held_symbols:
                    from trading.config import ALLOW_SHORT_SELLING, SHORT_ALLOWED_STRATEGIES
                    # For aggregator signals, check contributing strategies
                    strat_name = signal.strategy
                    if strat_name == "aggregator":
                        contributing = (signal.data or {}).get("contributing_strategies", [])
                        short_allowed = any(s in SHORT_ALLOWED_STRATEGIES for s in contributing)
                    else:
                        short_allowed = strat_name in SHORT_ALLOWED_STRATEGIES
                    if not ALLOW_SHORT_SELLING or not short_allowed:
                        console.print(f"  [dim]Skip SELL {signal.symbol} -- no position held[/dim]")
                        continue
                    # Allow short for permitted strategies

            # Market hours gate -- block ETF orders outside NYSE hours
            can_trade, reason = can_trade_now(signal.symbol)
            if not can_trade:
                blocked_count += 1
                # Queue signal for execution when market opens (expires in 8h)
                from trading.db.store import save_deferred_signal
                expires = (datetime.now(timezone.utc) + timedelta(hours=8)).isoformat()
                try:
                    save_deferred_signal(
                        symbol=signal.symbol,
                        action=signal.action,
                        strength=signal.strength,
                        strategy=signal.strategy,
                        reason=reason,
                        expires_at=expires,
                    )
                except Exception:
                    pass
                log_action(
                    "risk_block", "market_closed_queued",
                    symbol=signal.symbol,
                    details=f"Queued for market open: {reason}",
                )
                console.print(f"  [yellow]QUEUED {signal.symbol}: {reason}[/yellow]")
                continue

            # Volume gate — block BUY entries on low-volume assets
            if signal.action == "buy":
                try:
                    from trading.risk.volume_gate import compute_volume_ratio, compute_volume_trend
                    from trading.data.aster import alpaca_to_aster

                    aster_sym = alpaca_to_aster(signal.symbol)
                    if aster_sym:
                        vol_ratio = compute_volume_ratio(aster_sym)
                        vol_trend = compute_volume_trend(aster_sym) or 0.0
                        min_entry_vol = RISK.get("min_volume_ratio", 0.30)

                        if vol_ratio is not None and vol_ratio < min_entry_vol:
                            log_action(
                                "volume_block", "entry_blocked",
                                symbol=signal.symbol,
                                details=f"Volume {vol_ratio:.0%} of avg (min {min_entry_vol:.0%}), trend={vol_trend:+.2f}",
                                data={"volume_ratio": round(vol_ratio, 3), "volume_trend": round(vol_trend, 3)},
                            )
                            console.print(f"  [yellow]VOLUME BLOCK {signal.symbol} — volume {vol_ratio:.0%} below {min_entry_vol:.0%} threshold[/yellow]")
                            blocked_count += 1
                            continue
                except Exception as e:
                    log.debug("Volume entry gate failed for %s: %s", signal.symbol, e)

            # Size the order (volatility-adjusted + strategy budgets)
            order_value = calculate_order_size(
                signal, portfolio_value, buy_count
            )
            if order_value <= 0:
                console.print(f"  [dim]Skip {signal.symbol} -- too small or budget exhausted[/dim]")
                continue

            # Extra safety: don't exceed actual buying power
            buying_power = account.get("buying_power", float("inf"))
            if order_value > buying_power:
                order_value = max(buying_power - 10, 0)  # Leave $10 buffer
                if order_value <= 5:
                    console.print(f"  [yellow]Skip {signal.symbol} -- insufficient buying power[/yellow]")
                    continue

            # Risk check (correlation limits, crypto cap, etc.)
            risk_check = risk_mgr.check_trade(signal, order_value)
            if not risk_check.allowed:
                blocked_count += 1
                # Generate LLM explanation for the risk block (best-effort)
                block_explanation = None
                try:
                    from trading.llm.engine import explain_risk_block
                    sig_dict = {"symbol": signal.symbol, "action": signal.action,
                                "strategy": signal.strategy, "strength": signal.strength}
                    port_state = {"portfolio_value": portfolio_value, "order_value": order_value}
                    block_explanation = explain_risk_block(sig_dict, risk_check.reason, port_state)
                    if block_explanation and "LLM unavailable" in block_explanation:
                        block_explanation = None
                except Exception:
                    pass
                log_action(
                    "risk_block", "trade_blocked",
                    symbol=signal.symbol,
                    details=risk_check.reason,
                    data={"order_value": order_value,
                          "llm_explanation": block_explanation},
                )
                console.print(f"  [red]BLOCKED {signal.symbol}: {risk_check.reason}[/red]")
                continue

            # Compute trade targets (SL/TP) for server-side stop-loss
            stop_loss_price = None
            take_profit_price = None
            try:
                from trading.risk.manager import compute_trade_targets
                from trading.execution.router import get_crypto_quote
                entry_price = None
                if signal.data and signal.data.get("price"):
                    entry_price = signal.data["price"]
                if not entry_price:
                    try:
                        q = get_crypto_quote(signal.symbol)
                        entry_price = q.get("mid") or None
                    except Exception:
                        pass
                if entry_price and entry_price > 0:
                    targets = compute_trade_targets(
                        symbol=signal.symbol,
                        entry_price=entry_price,
                        order_value=order_value,
                        signal_strength=signal.strength,
                    )
                    stop_loss_price = targets.stop_loss_price
                    take_profit_price = targets.take_profit_price
            except Exception as e:
                log.debug("Could not compute trade targets for %s: %s", signal.symbol, e)

            # Pre-trade narration
            contributing = (signal.data or {}).get("contributing_strategies", [])
            ctx = contexts.get(contributing[0], {}) if contributing else {}
            narration = _narrate_trade(
                signal, order_value, portfolio_value, risk_check, ctx, stop_loss_price
            )
            log.info("PRE-TRADE: %s", narration)
            console.print(f"  [bold cyan]>> {narration}[/bold cyan]")
            log_action(
                "trade", "pre_trade_narration",
                symbol=signal.symbol,
                details=narration,
                data={
                    "action": signal.action,
                    "order_value": order_value,
                    "strength": signal.strength,
                    "strategy": signal.strategy,
                    "contributing": contributing,
                },
            )

            # Inject leverage from config
            from trading.config import get_leverage
            base_strategy = signal.strategy.split("+")[0]
            lev = get_leverage(base_strategy)
            signal.data = signal.data or {}
            signal.data["leverage"] = lev

            # Execute (with error handling for insufficient funds, etc.)
            try:
                order = _execute_order(signal.symbol, signal.action, notional=order_value,
                                       stop_loss_price=stop_loss_price, leverage=lev)
            except Exception as exec_err:
                log_action(
                    "error", "order_failed",
                    symbol=signal.symbol,
                    details=f"Order execution failed: {exec_err}",
                    data={"order_value": order_value, "action": signal.action},
                )
                log.error("Order failed for %s: %s", signal.symbol, exec_err)
                console.print(f"  [red]ORDER FAILED {signal.symbol}: {exec_err}[/red]")
                continue

            if order.get("status") in ("filled", "accepted", "new", "pending_new"):
                # Poll for fill data if not immediately available
                filled_qty = order.get("filled_qty")
                filled_price = order.get("filled_avg_price")
                if (not filled_qty or not filled_price) and order.get("id"):
                    from trading.execution.router import get_order_status
                    for _poll in range(3):
                        time.sleep(1)
                        try:
                            fill_info = get_order_status(order["id"], symbol=signal.symbol)
                            if fill_info.get("filled_qty"):
                                filled_qty = fill_info["filled_qty"]
                                filled_price = fill_info.get("filled_avg_price")
                                order["status"] = fill_info.get("status", order["status"])
                                break
                        except Exception:
                            pass

                qty_f = float(filled_qty) if filled_qty else 0
                price_f = float(filled_price) if filled_price else 0

                # -------------------------------------------------------
                # Partial fill handling
                # -------------------------------------------------------
                requested_qty = float(order.get("qty", 0))
                fill_ratio = (qty_f / requested_qty) if requested_qty > 0 else 1.0

                if 0 < fill_ratio < 0.80 and requested_qty > 0:
                    # Partial fill < 80%: cancel remainder, accept what we got
                    log.warning(
                        "Partial fill for %s: %.1f%% filled (%.6f / %.6f) "
                        "-- accepting partial, cancelling remainder",
                        signal.symbol, fill_ratio * 100, qty_f, requested_qty,
                    )
                    try:
                        from trading.execution.aster_client import aster_cancel_order
                        from trading.execution.router import _to_aster
                        aster_order_id = order.get("aster_order_id") or order.get("id")
                        aster_cancel_order(
                            _to_aster(signal.symbol),
                            order_id=int(aster_order_id),
                        )
                    except Exception as cancel_err:
                        log.debug("Cancel remainder for %s: %s", signal.symbol, cancel_err)

                    log_action(
                        "trade", "partial_fill",
                        symbol=signal.symbol,
                        details=f"Filled {fill_ratio:.0%} ({qty_f:.6f}/{requested_qty:.6f})",
                        data={
                            "filled_qty": qty_f,
                            "requested_qty": requested_qty,
                            "fill_ratio": fill_ratio,
                        },
                    )
                elif 0.80 <= fill_ratio < 1.0 and requested_qty > 0:
                    # Partial fill >= 80%: accept and adjust SL for actual qty
                    log.info(
                        "Near-complete fill for %s: %.1f%% -- accepting with adjusted qty",
                        signal.symbol, fill_ratio * 100,
                    )
                    if stop_loss_price and stop_loss_price > 0 and qty_f < requested_qty:
                        log.info(
                            "SL adjusted for actual fill qty: %.6f (was %.6f)",
                            qty_f, requested_qty,
                        )

                # Record fill quality for slippage analysis
                try:
                    from trading.execution.fill_analysis import record_fill
                    from trading.execution.router import get_crypto_quote
                    mid_price = price_f  # best available fallback
                    try:
                        quote = get_crypto_quote(signal.symbol)
                        if quote.get("mid", 0) > 0:
                            mid_price = quote["mid"]
                    except Exception:
                        pass
                    if qty_f > 0 and price_f > 0:
                        record_fill(
                            symbol=signal.symbol,
                            mid_at_signal=mid_price,
                            fill_price=price_f,
                            qty=qty_f,
                            side=signal.action,
                            notional=price_f * qty_f,
                        )
                except Exception as fill_err:
                    log.debug("Fill analysis recording failed: %s", fill_err)

                # Enrich entry reasoning with LLM (best-effort, non-blocking)
                enriched_reasoning = narration
                try:
                    from trading.llm.engine import generate_entry_reasoning
                    signal_dict = {
                        "symbol": signal.symbol, "action": signal.action,
                        "strategy": signal.strategy, "strength": signal.strength,
                        "reason": signal.reason,
                        "contributing": (signal.data or {}).get("contributing_strategies", []),
                    }
                    portfolio_ctx = {
                        "portfolio_value": portfolio_value,
                        "order_value": order_value,
                        "pct_of_portfolio": round(order_value / portfolio_value * 100, 1) if portfolio_value else 0,
                        "leverage": lev,
                        "stop_loss": stop_loss_price,
                        "take_profit": take_profit_price,
                    }
                    regime_ctx = {}
                    try:
                        from trading.intelligence.engine import generate_briefing
                        b = generate_briefing()
                        regime_ctx = {"regime": b.overall_regime, "score": b.overall_score}
                    except Exception:
                        pass
                    lessons = []
                    try:
                        from trading.intelligence.action_narrator import get_recent_lessons
                        lessons = get_recent_lessons(limit=5)
                    except Exception:
                        pass
                    llm_reasoning = generate_entry_reasoning(signal_dict, portfolio_ctx, regime_ctx, lessons)
                    if llm_reasoning and "LLM unavailable" not in llm_reasoning:
                        enriched_reasoning = llm_reasoning
                except Exception as llm_err:
                    log.debug("LLM entry reasoning failed (using template): %s", llm_err)

                # Use the primary contributing strategy instead of "aggregator"
                trade_strategy = signal.strategy
                if trade_strategy == "aggregator" and hasattr(signal, "data") and signal.data:
                    contributors = signal.data.get("contributing_strategies", [])
                    if contributors:
                        trade_strategy = contributors[0]  # Highest-strength contributor is first

                trade_id = insert_trade(
                    symbol=signal.symbol,
                    side=signal.action,
                    qty=qty_f,
                    price=price_f,
                    total=price_f * qty_f if (price_f and qty_f) else order_value,
                    strategy=trade_strategy,
                    status=order["status"],
                    alpaca_order_id=order.get("id"),
                    stop_loss_price=stop_loss_price,
                    take_profit_price=take_profit_price,
                    leverage=lev,
                    entry_reasoning=enriched_reasoning,
                )
                create_journal_entry(trade_id, signal, ctx, narration=narration)
                executed_count += 1
                log_action(
                    "trade", signal.action,
                    symbol=signal.symbol,
                    details=f"${order_value:.2f}",
                    result=order["status"],
                    data={
                        "trade_id": trade_id,
                        "qty": qty_f,
                        "price": price_f,
                    },
                )
                side_style = "green" if signal.action == "buy" else "red"
                console.print(
                    f"  [{side_style}]{signal.action.upper()} "
                    f"${order_value:.2f} {signal.symbol} -- {order['status']}[/]"
                )
                log.info("Executed %s $%.2f %s -> %s (qty=%.6f, price=%.2f)",
                         signal.action, order_value, signal.symbol, order["status"],
                         qty_f, price_f)
                # Notify
                _notify_safe(
                    notify_trade,
                    signal.symbol, signal.action, order_value,
                    price_f,
                    signal.strategy,
                )
            else:
                log_action(
                    "error", "order_rejected",
                    symbol=signal.symbol,
                    details=order.get("reason", order.get("status", "unknown")),
                    data={
                        "order_value": order_value,
                        "action": signal.action,
                        "strategy": signal.strategy,
                        "qty": order.get("qty", 0),
                    },
                )

        # ---------------------------------------------------------------
        # Phase 5: Post-trade sync (verify fills + pair trades for P&L)
        # ---------------------------------------------------------------
        try:
            run_sync()
        except Exception as e:
            log.warning("Post-trade sync warning: %s", e)
            console.print(f"[yellow]Post-trade sync warning: {e}[/yellow]")

        # ---------------------------------------------------------------
        # Phase 6: Record daily P&L snapshot (proper daily return calc)
        # ---------------------------------------------------------------
        try:
            log.info("Phase 6: recording P&L snapshot...")

            # Get positions — tolerate failure
            pos_value = 0.0
            try:
                positions = _get_positions()
                for p in (positions or []):
                    try:
                        mv = float(p.get("market_value") or 0)
                        if not mv:
                            qty = float(p.get("qty") or 0)
                            price = float(p.get("current_price") or p.get("avg_cost") or 0)
                            mv = qty * price
                        pos_value += mv
                    except (TypeError, ValueError):
                        continue
            except Exception as pos_err:
                log.warning("Phase 6: positions fetch failed (%s), using pos_value=0", pos_err)

            # Get account cash — tolerate failure
            cash = 0.0
            try:
                fresh_account = _get_account()
                cash = float(fresh_account.get("cash", 0) or 0)
            except Exception as acct_err:
                log.warning("Phase 6: account fetch failed (%s), using cash=0", acct_err)

            pv = cash + pos_value

            # If both failed, try to carry forward yesterday's value
            if pv <= 0:
                try:
                    with get_db() as conn:
                        last_row = conn.execute(
                            "SELECT portfolio_value, cash, positions_value FROM daily_pnl ORDER BY date DESC LIMIT 1"
                        ).fetchone()
                    if last_row:
                        pv = float(last_row["portfolio_value"])
                        cash = float(last_row["cash"])
                        pos_value = float(last_row["positions_value"])
                        log.warning("Phase 6: using last known P&L values (pv=$%.2f)", pv)
                except Exception:
                    pv = float(INITIAL_CAPITAL)
                    cash = float(INITIAL_CAPITAL)

            # Proper daily return: compare to yesterday's final portfolio value
            initial_str = get_setting("initial_capital")
            if initial_str:
                initial = float(initial_str)
            else:
                initial = float(INITIAL_CAPITAL)
                set_setting("initial_capital", str(initial))
            yesterday = (datetime.now(timezone.utc) - timedelta(days=1)).strftime("%Y-%m-%d")
            prev_pv = initial
            try:
                with get_db() as conn:
                    prev_row = conn.execute(
                        "SELECT portfolio_value FROM daily_pnl WHERE date = ? LIMIT 1",
                        (yesterday,)
                    ).fetchone()
                if prev_row:
                    prev_pv = float(prev_row["portfolio_value"])
            except Exception as prev_err:
                log.warning("Phase 6: prev P&L lookup failed (%s), using initial", prev_err)
            daily_ret = (pv - prev_pv) / prev_pv if prev_pv > 0 else 0.0

            # Cumulative return from initial capital (initial already set above)
            cum_ret = (pv - initial) / initial if initial > 0 else 0.0
            record_daily_pnl(pv, cash, pos_value, daily_ret, cum_ret)
            today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            log.info("Phase 6 OK: date=%s pv=$%.2f cash=$%.2f pos=$%.2f daily=%.4f cum=%.4f",
                     today_str, pv, cash, pos_value, daily_ret, cum_ret)
            log_action(
                "system", "pnl_recorded",
                details=f"P&L saved: date={today_str} pv=${pv:.2f} cash=${cash:.2f} pos=${pos_value:.2f}",
                data={"date": today_str, "portfolio_value": pv, "cash": cash, "positions_value": pos_value,
                      "daily_return": daily_ret, "cumulative_return": cum_ret},
            )
        except Exception as e:
            log.error("P&L snapshot failed: %s", e, exc_info=True)
            console.print(f"[red]P&L snapshot FAILED: {e}[/red]")
            log_action("error", "pnl_failed", details=f"Phase 6 P&L recording failed: {e}")

        # ---------------------------------------------------------------
        # Phase 7: Dust cleanup
        # ---------------------------------------------------------------
        try:
            from trading.execution.cleanup import close_dust_positions
            dust_closed = close_dust_positions()
            if dust_closed:
                log_action("cleanup", "dust_sweep", details=f"Closed {len(dust_closed)} dust positions: {', '.join(dust_closed)}")
        except Exception as e:
            log.warning("Dust cleanup failed: %s", e)

        # ---------------------------------------------------------------
        # Summary
        # ---------------------------------------------------------------
        log_action(
            "strategy_run", "cycle_complete",
            details=(
                f"Raw: {signal_count} | Consolidated: {len(consolidated)} | "
                f"Executed: {executed_count} | Blocked: {blocked_count}"
            ),
        )
        log.info(
            "Cycle complete: %d raw -> %d consolidated, %d executed, %d blocked",
            signal_count, len(consolidated), executed_count, blocked_count,
        )
        console.print(
            f"\n[bold]Cycle complete -- {signal_count} raw signals -> "
            f"{len(consolidated)} consolidated, "
            f"{executed_count} trades, {blocked_count} blocked[/bold]"
        )

        # Send cycle summary notification
        _notify_safe(notify_cycle_summary, signal_count, executed_count, blocked_count)

        # ---------------------------------------------------------------
        # Signal-to-execution funnel (Phase 5.3 monitoring)
        # ---------------------------------------------------------------
        try:
            import json as _json
            _cycle_elapsed = time.monotonic() - _cycle_start_time
            funnel_data = {
                "generated": signal_count,
                "consolidated": len(consolidated),
                "actionable": actionable_count,
                "risk_passed": actionable_count - blocked_count,
                "executed": executed_count,
                "blocked": blocked_count,
                "cycle_time_s": round(_cycle_elapsed, 2),
            }
            log_action(
                "funnel", "cycle_funnel",
                details=f"Gen:{signal_count} Con:{len(consolidated)} Act:{actionable_count} Exec:{executed_count}",
                data=funnel_data,
            )
        except Exception as _funnel_err:
            log.debug("Funnel tracking failed: %s", _funnel_err)

        # ---------------------------------------------------------------
        # Phase 7: Autonomous improvement cycle
        # ---------------------------------------------------------------
        # Agents analyze performance, risk, regime, and research gaps.
        # Safe actions are auto-applied; dangerous ones stored for review.
        try:
            from trading.intelligence.autonomous import run_autonomous_cycle
            auto_result = run_autonomous_cycle()
            auto_applied = auto_result.get("auto_applied", 0)
            auto_review = auto_result.get("needs_review", 0)
            auto_total = auto_result.get("total_recommendations", 0)
            if auto_total > 0:
                console.print(
                    f"\n[bold magenta]Autonomous: {auto_total} recommendations — "
                    f"{auto_applied} auto-applied, {auto_review} need review[/bold magenta]"
                )
                for action in auto_result.get("applied_actions", []):
                    console.print(
                        f"  [magenta]→ {action['action']}: {action['target']} — {action['result']}[/magenta]"
                    )
            else:
                console.print("[dim]Autonomous: no recommendations this cycle[/dim]")
        except Exception as e:
            log.warning("Autonomous cycle failed (non-fatal): %s", e)
            console.print(f"[yellow]Autonomous cycle skipped: {e}[/yellow]")

        # ---------------------------------------------------------------
        # Phase 8: Check operator alerts
        # ---------------------------------------------------------------
        try:
            from trading.monitor.operator_hooks import check_alerts
            check_alerts()
        except Exception as e:
            log.warning("Alert check failed (non-fatal): %s", e)

        # ---------------------------------------------------------------
        # Phase 8.1: Margin monitor — emergency close / reduce / warn
        # ---------------------------------------------------------------
        try:
            from trading.risk.margin_monitor import check_margin_health
            margin_actions = check_margin_health(positions or [])
            for ma in margin_actions:
                if ma["action"] == "emergency_close":
                    log_action("risk_block", "margin_emergency_close", symbol=ma["symbol"],
                               details=f"Margin distance {ma['margin_distance']:.1%} — EMERGENCY CLOSE")
                    console.print(f"[bold red]MARGIN EMERGENCY: {ma['symbol']} at {ma['margin_distance']:.1%}[/bold red]")
                    # Actually close the position
                    try:
                        from trading.execution.router import close_position
                        close_result = close_position(ma["symbol"])
                        log_action("trade", "margin_emergency_executed", symbol=ma["symbol"],
                                   details=f"Emergency close executed: {close_result}")
                        console.print(f"[bold red]EXECUTED emergency close for {ma['symbol']}[/bold red]")
                    except Exception as close_err:
                        log.error("FAILED to emergency close %s: %s", ma["symbol"], close_err)
                        log_action("error", "margin_emergency_failed", symbol=ma["symbol"],
                                   details=f"Emergency close FAILED: {close_err}")
                elif ma["action"] == "reduce_50":
                    log_action("risk_block", "margin_reduce", symbol=ma["symbol"],
                               details=f"Margin distance {ma['margin_distance']:.1%} — reduce position 50%")
                    console.print(f"[yellow]MARGIN WARNING: {ma['symbol']} at {ma['margin_distance']:.1%}[/yellow]")
                    # Actually reduce position by 50%
                    try:
                        from trading.execution.router import reduce_position
                        reduce_result = reduce_position(ma["symbol"], fraction=0.5)
                        log_action("trade", "margin_reduce_executed", symbol=ma["symbol"],
                                   details=f"50% reduction executed: {reduce_result}")
                        console.print(f"[yellow]EXECUTED 50% reduction for {ma['symbol']}[/yellow]")
                    except Exception as reduce_err:
                        log.error("FAILED to reduce %s: %s", ma["symbol"], reduce_err)
                        log_action("error", "margin_reduce_failed", symbol=ma["symbol"],
                                   details=f"Position reduction FAILED: {reduce_err}")
                elif ma["action"] == "warn":
                    log_action("system", "margin_warn", symbol=ma["symbol"],
                               details=f"Margin distance {ma['margin_distance']:.1%}")
        except Exception as e:
            log.error("Margin monitor failed: %s", e)

        # ---------------------------------------------------------------
        # Phase 8.2: Anomaly detection — track per-cycle metrics
        # ---------------------------------------------------------------
        try:
            from trading.monitor.anomaly import check_cycle_anomalies, log_anomalies
            _cycle_elapsed_s = time.monotonic() - _cycle_start_time
            anomalies = check_cycle_anomalies(
                signals_count=signal_count,
                exec_time_s=_cycle_elapsed_s,
                rejections=blocked_count,
                api_errors=0,
            )
            log_anomalies(anomalies)
            if anomalies:
                console.print(f"[yellow]Anomalies detected: {len(anomalies)}[/yellow]")
                for a in anomalies:
                    console.print(f"  [yellow]{a}[/yellow]")
        except Exception as e:
            log.debug("Anomaly detection failed (non-fatal): %s", e)

        # ---------------------------------------------------------------
        # Phase 8.3: Scale into winners — add to winning positions
        # ---------------------------------------------------------------
        try:
            scaled = _check_scale_in_winners(positions, portfolio_value)
            if scaled:
                console.print(f"[green]Scaled into {len(scaled)} winning positions[/green]")
                for s in scaled:
                    console.print(f"  [green]→ {s['symbol']} +${s['addon_value']:.2f} (unrealized +{s['current_pnl_pct']:.1%})[/green]")
        except Exception as e:
            log.debug("Scale-in check failed (non-fatal): %s", e)

        # ---------------------------------------------------------------
        # Phase 9: Record volume snapshots for learning
        # ---------------------------------------------------------------
        try:
            from trading.risk.volume_gate import record_volume_snapshot
            from trading.data.aster import alpaca_to_aster
            # Record for all symbols we have open positions in + top coins
            vol_symbols = set()
            for pos in _get_positions():
                a = alpaca_to_aster(pos["symbol"])
                if a:
                    vol_symbols.add(a)
            # Always track top liquid markets
            for coin in ("bitcoin", "ethereum", "solana"):
                from trading.config import ASTER_SYMBOLS
                a = ASTER_SYMBOLS.get(coin)
                if a:
                    vol_symbols.add(a)
            for vs in vol_symbols:
                record_volume_snapshot(vs)
            if vol_symbols:
                log.debug("Recorded volume snapshots for %d symbols", len(vol_symbols))
        except Exception as e:
            log.debug("Volume snapshot recording failed (non-fatal): %s", e)

        # ---------------------------------------------------------------
        # Phase 10: Generate narratives for this cycle's actions (background)
        # ---------------------------------------------------------------
        try:
            import threading
            def _generate_narratives():
                try:
                    from trading.intelligence.action_narrator import generate_missing_narratives
                    count = generate_missing_narratives(limit=30)
                    if count:
                        log.info("Generated %d action narratives", count)
                except Exception as ne:
                    log.debug("Narrative generation failed (non-fatal): %s", ne)
            threading.Thread(target=_generate_narratives, daemon=True, name="narrative-generator").start()
        except Exception:
            pass

    except Exception as e:
        log_action("error", "cycle_crash", details=str(e))
        log.exception("Cycle crashed: %s", e)
        console.print(f"[bold red]Cycle crashed: {e}[/bold red]")
        traceback.print_exc()
        try:
            from trading.monitor.notifications import notify_error
            _notify_safe(notify_error, str(e), "cycle_crash")
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Scale into winners — add to winning positions
# ---------------------------------------------------------------------------

def _check_scale_in_winners(positions, portfolio_value):
    """Scale into winning positions."""
    from trading.config import get_leverage, RISK
    from trading.db.store import get_setting, set_setting, log_action
    import json

    max_pos_pct = RISK.get("max_position_pct", 0.15)
    scaled = []
    for pos in (positions or []):
        pnl_pct = (pos.get("unrealized_pnlpc", 0) or 0)
        if pnl_pct < 0.05:  # Need >5% unrealized gain
            continue
        symbol = pos.get("symbol", "")
        # Check if already scaled this cycle
        key = f"scale_in_{symbol}"
        last = get_setting(key)
        if last:
            try:
                last_data = json.loads(last)
                from datetime import datetime, timezone, timedelta
                if datetime.fromisoformat(last_data.get("timestamp","")) > datetime.now(timezone.utc) - timedelta(hours=4):
                    continue
            except Exception:
                pass
        current_pct = abs(pos.get("market_value", 0)) / portfolio_value if portfolio_value else 0
        addon_pct = min(0.03, max_pos_pct - current_pct)  # 3% or remaining room
        if addon_pct < 0.005:
            continue
        addon_value = portfolio_value * addon_pct
        scaled.append({"symbol": symbol, "addon_value": addon_value, "current_pnl_pct": pnl_pct})
        set_setting(key, json.dumps({"timestamp": datetime.now(timezone.utc).isoformat()}))
        log_action("scale_in", f"Scale into winner {symbol} (+${addon_value:.2f})", symbol=symbol)
    return scaled


# ---------------------------------------------------------------------------
# 12-hour trade analysis — now handled by Position Review Agent in
# trading.intelligence.autonomous._position_review_agent_think()
# The agent runs every autonomous cycle and self-throttles to 12h intervals.
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Stop-loss + take-profit checker (runs every 15 minutes)
# ---------------------------------------------------------------------------

def check_stop_losses():
    """Check all positions for stop-loss and take-profit/trailing-stop triggers."""
    from trading.risk.profit_manager import check_profit_targets

    try:
        account = _get_account()
        positions = _get_positions()

        if not positions:
            return

        tracker = _get_profit_tracker()

        # -- 1. Take-profit / trailing stop checks --
        profit_actions = check_profit_targets(positions, tracker)
        for action in profit_actions:
            symbol = normalize_symbol(action["symbol"])
            reason = action["reason"]
            pos_side = action.get("pos_side", "long")
            exit_side = "buy" if pos_side == "short" else "sell"
            console.print(f"[bold yellow]{action['action'].upper()}: {symbol} ({pos_side}) -- {reason}[/]")
            log_action(
                "profit_mgmt", action["action"],
                symbol=symbol,
                details=reason,
                data={"pnl_pct": action["pnl_pct"], "qty": action["qty"], "pos_side": pos_side},
            )
            try:
                order = _execute_order(symbol, exit_side, qty=action["qty"])
            except Exception as e:
                log.error("Profit management %s failed for %s: %s", exit_side, symbol, e)
                log_action("trade", f"{action['action']}_{exit_side}_failed", symbol=symbol,
                           result="error", details=f"Order execution failed: {e}")
                continue

            if order.get("status") in ("filled", "accepted", "new", "pending_new"):
                exit_price = float(order.get("filled_avg_price") or 0)
                insert_trade(
                    symbol=symbol,
                    side=exit_side,
                    qty=action["qty"],
                    price=exit_price,
                    total=action["qty"] * exit_price,
                    strategy=f"profit_mgmt_{action['action']}",
                    status=order["status"],
                    alpaca_order_id=order.get("id"),
                )
                # Immediately close matching entry trades so open/recent tables stay in sync
                try:
                    from trading.db.store import close_matching_entry_trades
                    close_matching_entry_trades(symbol, exit_price, action["qty"], exit_side=exit_side)
                except Exception as cmt_err:
                    log.warning("close_matching_entry_trades failed for %s: %s", symbol, cmt_err)
                log_action("trade", f"{action['action']}_{exit_side}", symbol=symbol, result=order["status"])
                tracker.remove(symbol)
                try:
                    from trading.monitor.notifications import notify_stop_loss
                    _notify_safe(notify_stop_loss, symbol, action["pnl_pct"] * 100, action["qty"])
                except Exception:
                    pass
            else:
                log.warning("Profit exit order for %s returned status: %s", symbol, order.get("status"))
                log_action("trade", f"{action['action']}_{exit_side}_failed", symbol=symbol,
                           result=order.get("status"), details=f"Order not filled: {order}")

        # -- 2. Hard stop-loss checks --
        for pos in positions:
            pnl_pct = pos.get("unrealized_pnl_pct", 0) / 100 if pos.get("unrealized_pnl_pct") else 0
            if pnl_pct <= -RISK["stop_loss_pct"]:
                symbol = normalize_symbol(pos["symbol"])
                # Skip if already exited by profit manager above
                if any(normalize_symbol(a["symbol"]) == symbol for a in profit_actions):
                    continue

                pos_side = pos.get("side", "long")
                exit_side = "buy" if pos_side == "short" else "sell"
                console.print(f"[bold red]STOP LOSS triggered: {symbol} ({pos_side}) at {pnl_pct*100:.1f}%[/]")
                log_action(
                    "stop_loss", "triggered",
                    symbol=symbol,
                    details=f"P&L: {pnl_pct*100:.1f}% ({pos_side})",
                    data={"pnl_pct": pnl_pct, "qty": pos["qty"], "pos_side": pos_side},
                )
                try:
                    order = _execute_order(symbol, exit_side, qty=pos["qty"])
                except Exception as e:
                    log.error("Stop-loss %s failed for %s: %s", exit_side, symbol, e)
                    log_action("trade", f"stop_loss_{exit_side}_failed", symbol=symbol,
                               result="error", details=f"Order execution failed: {e}")
                    continue

                if order.get("status") in ("filled", "accepted", "new", "pending_new"):
                    sl_price = float(order.get("filled_avg_price") or 0)
                    insert_trade(
                        symbol=symbol,
                        side=exit_side,
                        qty=pos["qty"],
                        price=sl_price,
                        total=pos["qty"] * sl_price,
                        strategy="stop_loss",
                        status=order["status"],
                        alpaca_order_id=order.get("id"),
                    )
                    # Immediately close matching entry trades so open/recent tables stay in sync
                    try:
                        from trading.db.store import close_matching_entry_trades
                        close_matching_entry_trades(symbol, sl_price, pos["qty"], exit_side=exit_side)
                    except Exception as cmt_err:
                        log.warning("close_matching_entry_trades failed for %s: %s", symbol, cmt_err)
                    log_action("trade", f"stop_loss_{exit_side}", symbol=symbol, result=order["status"])
                    tracker.remove(symbol)
                    try:
                        from trading.monitor.notifications import notify_stop_loss
                        _notify_safe(notify_stop_loss, symbol, pnl_pct * 100, pos["qty"])
                    except Exception:
                        pass
                else:
                    log.warning("Stop-loss exit order for %s returned status: %s", symbol, order.get("status"))
                    log_action("trade", f"stop_loss_{exit_side}_failed", symbol=symbol,
                               result=order.get("status"), details=f"Order not filled: {order}")

        # -- 2.5. Passive loss detection — catch positions that slipped through stops --
        try:
            from trading.risk.margin_monitor import check_passive_loss_accumulation
            passive_alerts = check_passive_loss_accumulation(positions, stop_loss_pct=RISK["stop_loss_pct"])
            for alert in passive_alerts:
                symbol = normalize_symbol(alert["symbol"])
                # Skip if already handled by profit mgr or stop-loss above
                if any(normalize_symbol(a["symbol"]) == symbol for a in profit_actions):
                    continue
                if alert["severity"] == "critical":
                    pos_side = alert["side"]
                    exit_side = "buy" if pos_side == "short" else "sell"
                    console.print(f"[bold red]PASSIVE LOSS DETECTED: {symbol} ({pos_side}) at {alert['loss_pct']*100:.1f}%[/]")
                    log_action(
                        "passive_loss", "emergency_close",
                        symbol=symbol,
                        details=alert["reason"],
                        data={"loss_pct": alert["loss_pct"], "qty": alert["qty"], "side": pos_side},
                    )
                    try:
                        order = _execute_order(symbol, exit_side, qty=alert["qty"])
                        if order.get("status") in ("filled", "accepted", "new", "pending_new"):
                            exit_price = float(order.get("filled_avg_price") or 0)
                            insert_trade(
                                symbol=symbol, side=exit_side, qty=alert["qty"],
                                price=exit_price, total=alert["qty"] * exit_price,
                                strategy="passive_loss_recovery", status=order["status"],
                                alpaca_order_id=order.get("id"),
                            )
                            try:
                                from trading.db.store import close_matching_entry_trades
                                close_matching_entry_trades(symbol, exit_price, alert["qty"], exit_side=exit_side)
                            except Exception:
                                pass
                            log_action("trade", "passive_loss_closed", symbol=symbol, result=order["status"])
                            tracker.remove(symbol)
                            console.print(f"[bold red]CLOSED passive loser {symbol} at ${exit_price:.2f}[/]")
                        else:
                            log.warning("Passive loss exit for %s returned status: %s", symbol, order.get("status"))
                            log_action("trade", "passive_loss_close_failed", symbol=symbol,
                                       result=order.get("status"), details=f"Order not filled: {order}")
                    except Exception as e:
                        log.error("Passive loss close failed for %s: %s", symbol, e)
                        log_action("trade", "passive_loss_close_failed", symbol=symbol,
                                   result="error", details=f"Order execution failed: {e}")
                elif alert["severity"] == "warning":
                    log_action("system", "passive_loss_warning", symbol=symbol, details=alert["reason"])
        except Exception as e:
            log.debug("Passive loss detection error: %s", e, exc_info=True)

        # -- 3. Volume dry-up exit check --
        # Close positions where volume has died (the move is over).
        # Only exit if position is profitable or near break-even to avoid
        # compounding losses — deep losers should be handled by stop-loss.
        try:
            from trading.risk.volume_gate import compute_volume_ratio, compute_volume_trend
            from trading.data.aster import alpaca_to_aster

            vol_exit_ratio = RISK.get("volume_exit_ratio", 0.20)
            already_sold = {normalize_symbol(a["symbol"]) for a in profit_actions}
            for pos in positions:
                symbol = normalize_symbol(pos["symbol"])
                if symbol in already_sold:
                    continue
                aster_sym = alpaca_to_aster(symbol)
                if not aster_sym:
                    continue
                ratio = compute_volume_ratio(aster_sym)
                if ratio is None:
                    continue
                trend = compute_volume_trend(aster_sym) or 0.0

                # Exit if volume is below absolute threshold
                # OR if volume is low-ish AND rapidly fading
                volume_dead = ratio < vol_exit_ratio
                volume_fading_fast = ratio < 0.50 and trend < -0.40
                if not volume_dead and not volume_fading_fast:
                    continue

                # Only exit if P&L is not deeply negative (> -2%)
                pnl_pct = pos.get("unrealized_pnl_pct", 0) / 100 if pos.get("unrealized_pnl_pct") else 0
                if pnl_pct < -0.02:
                    log.info("Volume dry for %s (ratio=%.0f%% trend=%.2f) but P&L %.1f%% — keeping for stop-loss",
                             symbol, ratio * 100, trend, pnl_pct * 100)
                    continue

                pos_side = pos.get("side", "long")
                exit_side = "buy" if pos_side == "short" else "sell"
                exit_reason = "fading fast" if volume_fading_fast and not volume_dead else "below threshold"
                console.print(f"[bold yellow]VOLUME EXIT: {symbol} ({pos_side}) — volume {ratio:.0%} ({exit_reason})[/]")
                log_action(
                    "volume_exit", "triggered",
                    symbol=symbol,
                    details=f"Volume {ratio:.0%} trend={trend:+.2f} ({exit_reason}), P&L {pnl_pct*100:.1f}% ({pos_side})",
                    data={"volume_ratio": round(ratio, 3), "volume_trend": round(trend, 3), "pnl_pct": pnl_pct, "qty": pos["qty"], "pos_side": pos_side},
                )
                try:
                    order = _execute_order(symbol, exit_side, qty=pos["qty"])
                except Exception as e:
                    log.error("Volume exit %s failed for %s: %s", exit_side, symbol, e)
                    log_action("trade", f"volume_exit_{exit_side}_failed", symbol=symbol,
                               result="error", details=f"Order execution failed: {e}")
                    continue

                if order.get("status") in ("filled", "accepted", "new", "pending_new"):
                    vol_exit_price = float(order.get("filled_avg_price") or 0)
                    insert_trade(
                        symbol=symbol,
                        side=exit_side,
                        qty=pos["qty"],
                        price=vol_exit_price,
                        total=pos["qty"] * vol_exit_price,
                        strategy="volume_exit",
                        status=order["status"],
                        alpaca_order_id=order.get("id"),
                    )
                    # Immediately close matching entry trades so open/recent tables stay in sync
                    try:
                        from trading.db.store import close_matching_entry_trades
                        close_matching_entry_trades(symbol, vol_exit_price, pos["qty"], exit_side=exit_side)
                    except Exception as cmt_err:
                        log.warning("close_matching_entry_trades failed for %s: %s", symbol, cmt_err)
                    log_action("trade", f"volume_exit_{exit_side}", symbol=symbol, result=order["status"])
                    tracker.remove(symbol)
                    already_sold.add(symbol)
                else:
                    log.warning("Volume exit order for %s returned status: %s", symbol, order.get("status"))
                    log_action("trade", f"volume_exit_{exit_side}_failed", symbol=symbol,
                               result=order.get("status"), details=f"Order not filled: {order}")
        except Exception as e:
            log.debug("Volume exit check error: %s", e, exc_info=True)

        # -- 4. Post-check sync --
        try:
            from trading.execution.sync import sync_positions
            sync_positions()
        except Exception:
            pass

    except Exception as e:
        log_action("error", "stop_loss_check_error", details=str(e))
        log.error("Stop-loss check error: %s", e)
        console.print(f"[red]Stop-loss check error: {e}[/red]")


# ---------------------------------------------------------------------------
# Daily journal generation (automated)
# ---------------------------------------------------------------------------

def run_daily_journal():
    """Auto-generate a daily trading journal entry and store it in the action log."""
    try:
        from trading.llm.engine import generate_journal
        from trading.db.store import get_trades, get_daily_pnl, get_signals, get_action_log
        from trading.execution.router import get_positions_from_aster

        trades = get_trades(limit=15)
        positions = get_positions_from_aster()[:10]
        pnl = get_daily_pnl(limit=7)
        signals = get_signals(limit=10)
        actions = get_action_log(limit=10)

        journal = generate_journal(trades, positions, pnl, signals, actions)
        if journal and "LLM unavailable" not in journal:
            log_action("journal", "daily_journal", details=journal[:200],
                       data={"content": journal, "type": "daily"})
            log.info("Daily journal generated (%d chars)", len(journal))
            console.print("[green]Daily journal generated.[/green]")
        else:
            log.debug("Daily journal skipped — LLM unavailable")
    except Exception as e:
        log.warning("Daily journal generation failed (non-fatal): %s", e)


# ---------------------------------------------------------------------------
# Weekly review + adaptation analysis
# ---------------------------------------------------------------------------

def run_weekly_review():
    """Generate a weekly performance review and suggest adaptations."""
    try:
        from trading.learning.reviewer import generate_review
        generate_review("weekly")
        log_action("review", "weekly_review_generated")
        log.info("Weekly review generated")
        console.print("[green]Weekly review generated.[/green]")
    except Exception as e:
        log_action("error", "review_error", details=str(e))
        log.error("Review error: %s", e)

    # Generate LLM-powered weekly synthesis
    try:
        from trading.llm.engine import generate_weekly_synthesis
        from trading.intelligence.action_narrator import get_recent_lessons
        from trading.db.store import get_trades, get_daily_pnl, get_action_log
        journal_entries = get_action_log(limit=50)
        lessons = get_recent_lessons(limit=15)
        strategies = []
        try:
            from trading.monitor.web import _get_strategies
            strategies = _get_strategies()
        except Exception:
            pass
        pnl_hist = get_daily_pnl(limit=7)
        synthesis = generate_weekly_synthesis(journal_entries, lessons, strategies, pnl_hist)
        if synthesis and "LLM unavailable" not in synthesis:
            log_action("journal", "weekly_synthesis", details=synthesis[:200],
                       data={"content": synthesis, "type": "weekly"})
            log.info("Weekly LLM synthesis generated (%d chars)", len(synthesis))
    except Exception as e:
        log.debug("Weekly LLM synthesis failed (non-fatal): %s", e)

    # Also run adaptation analysis
    try:
        from trading.learning.adaptor import analyze_and_suggest
        suggestions = analyze_and_suggest()
        if suggestions:
            log_action("system", "adaptations_suggested",
                       details=f"{len(suggestions)} parameter changes suggested")
            log.info("Suggested %d parameter adaptations", len(suggestions))
            console.print(f"[magenta]{len(suggestions)} adaptation suggestions generated[/]")
    except Exception as e:
        log.warning("Adaptation analysis failed: %s", e)

    # Run strategy research cycle — discover gaps and update catalog
    try:
        from trading.intelligence.strategy_researcher import run_research_cycle
        research = run_research_cycle()
        log_action("research", "strategy_research",
                   details=research.summary(),
                   data=research.to_dict())
        log.info("Strategy research: %s", research.summary())
        console.print(f"[cyan]{research.summary()}[/cyan]")
    except Exception as e:
        log.warning("Strategy research cycle failed: %s", e)


# ---------------------------------------------------------------------------
# Autonomous approval cycle — process all pending recommendations
# ---------------------------------------------------------------------------

def process_pending_approvals():
    """Process any pending agent recommendations with full autonomy.

    Runs every 30 minutes. Picks up any recommendations that were
    stored as 'pending' (from before full autonomy was enabled, or
    from edge cases) and auto-applies them.
    """
    try:
        from trading.db.store import get_pending_recommendations, resolve_recommendation
        from trading.intelligence.autonomous import _execute_safe_recommendations

        pending = get_pending_recommendations()
        if not pending:
            return

        log.info("Processing %d pending recommendations", len(pending))
        console.print(f"[magenta]Processing {len(pending)} pending approvals...[/magenta]")

        # Convert DB rows to recommendation dicts for the executor
        recs = []
        for p in pending:
            data = p.get("data", {})
            if isinstance(data, str):
                import json as _json
                try:
                    data = _json.loads(data)
                except Exception:
                    data = {}
            data["auto_approve"] = True  # Force auto-approve

            recs.append({
                "from_agent": p["from_agent"],
                "to_agent": p["to_agent"],
                "category": p["category"],
                "action": p["action"],
                "target": p.get("target", ""),
                "reasoning": p["reasoning"],
                "data": data,
                "_pending_id": p["id"],
            })

        # Execute all pending recommendations
        applied = _execute_safe_recommendations(recs)

        # Resolve the original pending entries
        for p in pending:
            resolve_recommendation(p["id"], "auto_approved", "Processed by autonomous approval cycle")

        if applied:
            log_action(
                "autonomous", "pending_approvals_processed",
                details=f"Auto-approved {len(applied)} pending recommendations",
            )
            for a in applied:
                console.print(f"  [magenta]→ {a['action']}: {a['target']} — {a['result']}[/magenta]")

    except Exception as e:
        log.warning("Pending approvals processing failed: %s", e)


# ---------------------------------------------------------------------------
# Startup validation — quick sanity backtest
# ---------------------------------------------------------------------------

def _run_startup_validation():
    """Run a quick sanity backtest to validate strategies and data sources."""
    from trading.config import RUN_STARTUP_BACKTEST
    if not RUN_STARTUP_BACKTEST:
        log.info("Startup backtest skipped (RUN_STARTUP_BACKTEST=false)")
        return

    log.info("Running startup validation backtest...")
    try:
        from trading.backtest.engine import Backtester, _fetch_historical_data
        from trading.config import STRATEGY_ENABLED
        from datetime import timedelta

        # Pick the first 3 enabled strategies for a quick validation
        enabled = [name for name, on in STRATEGY_ENABLED.items() if on][:3]
        if not enabled:
            log.warning("No strategies enabled — skipping startup backtest")
            return

        coins = ["bitcoin", "ethereum", "solana"]
        end_date = datetime.now(timezone.utc)
        start_date = end_date - timedelta(days=30)
        start_str = start_date.strftime("%Y-%m-%d")
        end_str = end_date.strftime("%Y-%m-%d")

        # Fetch historical data once
        historical_data = _fetch_historical_data(coins, start_str, end_str)
        if not historical_data:
            log.warning("STARTUP VALIDATION WARNING: No historical data fetched. "
                       "Check data sources.")
            return

        total_signals = 0
        for strat_name in enabled:
            try:
                bt = Backtester(starting_capital=10_000)
                result = bt.run(strat_name, historical_data, start_str, end_str)
                strat_signals = len(result.signals) if hasattr(result, 'signals') else 0
                total_signals += strat_signals
                log.info("Startup backtest %s: %d signals, Sharpe=%.2f, Win Rate=%.1f%%",
                        strat_name, strat_signals,
                        result.metrics.get("sharpe_ratio", 0),
                        result.metrics.get("win_rate", 0) * 100)
            except Exception as e:
                log.warning("Startup backtest for %s failed (non-fatal): %s", strat_name, e)

        if total_signals == 0:
            log.warning("STARTUP VALIDATION WARNING: Zero signals generated in 30-day backtest. "
                       "Check data sources and strategy configuration.")
        else:
            log.info("Startup validation passed: %d total signals across %d strategies",
                    total_signals, len(enabled))
    except Exception as e:
        log.warning("Startup validation backtest failed (non-fatal): %s", e)


# ---------------------------------------------------------------------------
# Daemon entry point
# ---------------------------------------------------------------------------

def start_daemon(interval_hours=4, paper=False):
    """Start the autonomous trading daemon."""
    if paper:
        import trading.config as cfg
        cfg.TRADING_MODE = "paper"

    # Initialize structured logging
    from trading.logging_config import setup_logging
    setup_logging(level="INFO")

    init_db()

    # Restore autonomous agent state (strategy enables, thresholds, budgets, risk)
    # so changes from previous cycles survive process restarts / deploys
    try:
        from trading.intelligence.autonomous import load_persisted_state
        load_persisted_state()
    except Exception as e:
        log.warning("Could not restore autonomous state: %s", e)

    # Initialize persistent profit tracker
    _get_profit_tracker()

    mode = "PAPER" if TRADING_MODE == "paper" or paper else "LIVE"
    console.print(f"\n[bold green]{'='*60}[/]")
    console.print(f"[bold green]  OT-CORP. AUTONOMOUS TRADER v5.0 -- {mode} MODE[/bold green]")
    console.print(f"[bold green]  Self-Evolving Trading System[/bold green]")
    console.print(f"[bold green]  Execution: AsterDex Perpetual Futures[/bold green]")
    console.print(f"[bold green]{'='*60}[/]")
    console.print(f"  Trading cycle:       every {interval_hours} hours")
    console.print(f"  Stop/profit check:   every 15 minutes")
    console.print(f"  Signal aggregation:  enabled (dedup + conflict resolution)")
    console.print(f"  Dynamic allocation:  confluence + regime + performance tilt")
    console.print(f"  Autonomous agents:   5 agents (perf, risk, regime, research, learning)")
    console.print(f"  Agent conversation:  continuous self-improvement loop")
    console.print(f"  Auto-disable:        strategies with <25% win rate")
    console.print(f"  Auto-rebalance:      shift capital to winners")
    console.print(f"  Risk auto-tighten:   at 10% drawdown, halt at 18%")
    console.print(f"  Regime adaptation:   defensive posture in bearish markets")
    console.print(f"  Strategy research:   weekly gap analysis + priority queue")
    console.print(f"  Knowledge base:      continuous learning from outcomes")
    console.print(f"  Dashboard:           http://localhost:5050")
    console.print(f"[bold green]{'='*60}[/]\n")

    log.info("Daemon v3.0 started in %s mode, interval=%dh", mode, interval_hours)
    log_action("scheduler", "daemon_started", details=f"Mode: {mode}, Interval: {interval_hours}h, Version: v3.0")

    # Notify on start
    try:
        from trading.monitor.notifications import notify
        _notify_safe(notify, "Daemon Started", f"Trading daemon v3.0 started in {mode} mode", "info")
    except Exception:
        pass

    # Note: AsterDex orders are immediate (market orders) — no orphaned order reconciliation needed
    log.info("AsterDex primary venue — skipping Alpaca order reconciliation")

    # Start WebSocket price feed (best-effort, falls back to REST)
    try:
        from trading.data.ws_feed import start_ws_feed
        from trading.config import ASTER_SYMBOLS
        ws_symbols = [s for s in ASTER_SYMBOLS.values() if s]
        if ws_symbols:
            start_ws_feed(ws_symbols[:20])  # Top 20 symbols
            console.print(f"[dim]WebSocket feed started for {min(len(ws_symbols), 20)} symbols[/dim]")
    except Exception as e:
        log.debug("WebSocket feed start failed (non-fatal, using REST): %s", e)

    # -----------------------------------------------------------------------
    # One-time P&L migrations — run at startup, NOT in trading cycle
    # These hold the DB open for a while; doing them in the cycle blocks
    # record_daily_pnl() and caused the P&L chart to stop updating.
    # -----------------------------------------------------------------------
    try:
        from trading.db.store import get_setting, set_setting, get_db
        initial = float(os.environ.get("INITIAL_CAPITAL", os.environ.get("PAPER_BALANCE", 1000)))

        # Mark v1/v2 as done so they never block the cycle
        if not get_setting("pnl_recalc_done"):
            set_setting("pnl_recalc_done", "true")
        if not get_setting("pnl_recalc_v2_done"):
            set_setting("pnl_recalc_v2_done", "true")

        if not get_setting("pnl_purge_v3_done"):
            log.info("Running one-time P&L v3 purge at startup...")
            with get_db() as db:
                rows = db.execute(
                    "SELECT date, portfolio_value FROM daily_pnl ORDER BY date ASC"
                ).fetchall()
                if rows:
                    prev_val = initial
                    for row in rows:
                        pv = row["portfolio_value"]
                        daily_ret = (pv - prev_val) / prev_val if prev_val > 0 else 0
                        cum_ret = (pv - initial) / initial if initial > 0 else 0
                        db.execute(
                            "UPDATE daily_pnl SET daily_return = ?, cumulative_return = ? WHERE date = ?",
                            (daily_ret, cum_ret, row["date"]),
                        )
                        prev_val = pv
            set_setting("pnl_purge_v3_done", "true")
            log.info("P&L v3 purge complete: recalculated %d records", len(rows) if rows else 0)
    except Exception as e:
        log.error("P&L v3 startup purge failed: %s", e)

    # -----------------------------------------------------------------------
    # One-time orphan trade cleanup — close stale open entries (buy AND
    # sell/short) from before sell-tracking was added.  Futures trading
    # means both sides can be open entries.  Runs once then sets a flag.
    # -----------------------------------------------------------------------
    try:
        if not get_setting("orphan_cleanup_v2_done"):
            from trading.db.store import get_open_trades, close_trade
            log.info("Running one-time orphan trade cleanup v2...")
            open_trades = get_open_trades()
            cleaned = 0
            for entry in open_trades:
                side = entry.get("side", "").lower()
                if side not in ("buy", "sell", "short"):
                    continue
                closing_side = "sell" if side == "buy" else "buy"
                sym = entry.get("symbol", "")
                from trading.db.store import symbol_variants
                variants = symbol_variants(sym)
                placeholders = ",".join("?" for _ in variants)
                entry_ts = entry.get("timestamp", "")
                with get_db() as db:
                    # Check if there's an opposite-side trade (exit) after this entry
                    exit_row = db.execute(
                        f"SELECT price FROM trades WHERE symbol IN ({placeholders}) "
                        f"AND side=? AND timestamp > ? LIMIT 1",
                        variants + [closing_side, entry_ts],
                    ).fetchone()
                    # Or a newer same-side entry (re-entry after unknown close)
                    newer_entry = db.execute(
                        f"SELECT id FROM trades WHERE symbol IN ({placeholders}) "
                        f"AND side=? AND timestamp > ? AND id != ? LIMIT 1",
                        variants + [side, entry_ts, entry["id"]],
                    ).fetchone()
                if exit_row or newer_entry:
                    exit_price = exit_row["price"] if exit_row and exit_row["price"] else (entry.get("price") or 0)
                    entry_price = entry.get("price") or 0
                    qty = entry.get("qty") or 0
                    if entry_price > 0:
                        if side == "buy":
                            pnl = (exit_price - entry_price) * qty
                        else:
                            pnl = (entry_price - exit_price) * qty
                    else:
                        pnl = 0.0
                    close_trade(entry["id"], exit_price, round(pnl, 2))
                    cleaned += 1
            set_setting("orphan_cleanup_v2_done", "true")
            log.info("Orphan cleanup v2 complete: closed %d stale entry trades", cleaned)
    except Exception as e:
        log.error("Orphan cleanup v2 failed: %s", e)

    # -----------------------------------------------------------------------
    # One-time cleanup v3 — fix stale trades caused by symbol format mismatch.
    # Entries stored as "AVAX/USD" but exits as "AVAXUSD" were never paired.
    # Uses pair_trades() with normalized bucketing + broker position check.
    # -----------------------------------------------------------------------
    try:
        if not get_setting("orphan_cleanup_v3_done"):
            log.info("Running one-time orphan cleanup v3 (symbol format mismatch)...")
            from trading.execution.sync import pair_trades
            paired = pair_trades()
            # Also reconcile against current broker positions
            try:
                positions = _get_positions()
                from trading.monitor.web import _reconcile_orphan_trades
                reconciled = _reconcile_orphan_trades(positions)
            except Exception:
                reconciled = 0
            set_setting("orphan_cleanup_v3_done", "true")
            log.info("Orphan cleanup v3 complete: paired %d, reconciled %d", paired, reconciled)
    except Exception as e:
        log.error("Orphan cleanup v3 failed: %s", e)

    # Run startup validation backtest (if enabled)
    _run_startup_validation()

    # Run immediately on start
    run_trading_cycle()

    # ---------------------------------------------------------------------------
    # Startup sync — run any scheduled tasks that should have fired today
    # ---------------------------------------------------------------------------
    try:
        from trading.db.store import get_action_log as _startup_get_al
        _today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        _today_actions = _startup_get_al(limit=100, category="journal")
        _has_daily = any(
            a.get("timestamp", "")[:10] == _today
            and isinstance(a.get("data"), dict)
            and a["data"].get("type") == "daily"
            for a in _today_actions
        )
        if not isinstance(_today_actions[0].get("data"), dict) if _today_actions else True:
            # data might be JSON string — parse it
            import json as _json_startup
            _has_daily = any(
                a.get("timestamp", "")[:10] == _today
                and (_json_startup.loads(a["data"]) if isinstance(a.get("data"), str) else a.get("data", {})).get("type") == "daily"
                for a in _today_actions
            )
        if not _has_daily:
            log.info("No daily journal for today — generating on startup")
            run_daily_journal()

        # Check if weekly review is due (if today is Sunday and none generated this week)
        now_utc = datetime.now(timezone.utc)
        if now_utc.weekday() == 6:  # Sunday
            _week_start = (now_utc - timedelta(days=1)).strftime("%Y-%m-%d")
            _has_weekly = any(
                a.get("timestamp", "")[:10] >= _week_start
                and ((_json_startup.loads(a["data"]) if isinstance(a.get("data"), str) else a.get("data", {})).get("type") == "weekly" if a.get("data") else False)
                for a in _today_actions
            )
            if not _has_weekly:
                log.info("No weekly review this week — generating on startup")
                run_weekly_review()
    except Exception as e:
        log.debug("Startup journal/review sync failed (non-fatal): %s", e)

    # Schedule recurring tasks
    schedule.every(interval_hours).hours.do(run_trading_cycle)
    schedule.every(15).minutes.do(check_stop_losses)
    schedule.every(30).minutes.do(process_pending_approvals)
    schedule.every().day.at("23:55").do(run_daily_journal)
    schedule.every().sunday.at("00:00").do(run_weekly_review)
    # Position review now runs as part of run_autonomous_cycle() — no separate schedule needed

    # Graceful shutdown via SIGTERM/SIGINT
    _shutdown_requested = False

    def _handle_shutdown(signum, frame):
        nonlocal _shutdown_requested
        _shutdown_requested = True
        sig_name = signal_mod.Signals(signum).name
        log.info("Received %s — completing current cycle before shutdown", sig_name)
        console.print(f"\n[yellow]Received {sig_name} — shutting down gracefully...[/yellow]")

    signal_mod.signal(signal_mod.SIGTERM, _handle_shutdown)
    signal_mod.signal(signal_mod.SIGINT, _handle_shutdown)

    consecutive_errors = 0
    max_consecutive_errors = 10
    backoff_minutes = 5

    try:
        while not _shutdown_requested:
            try:
                schedule.run_pending()
                consecutive_errors = 0  # Reset on success
            except KeyboardInterrupt:
                break
            except Exception as exc:
                consecutive_errors += 1
                log.error("Daemon loop error (%d/%d): %s", consecutive_errors, max_consecutive_errors, exc)
                log_action("error", "daemon_loop", details=f"Error {consecutive_errors}/{max_consecutive_errors}: {exc}")

                if consecutive_errors >= max_consecutive_errors:
                    pause_msg = f"Too many consecutive errors ({consecutive_errors}), pausing {backoff_minutes}m"
                    log.warning(pause_msg)
                    console.print(f"[red]{pause_msg}[/red]")
                    log_action("scheduler", "daemon_backoff", details=pause_msg)
                    try:
                        from trading.monitor.notifications import notify
                        _notify_safe(notify, "Daemon Backoff", pause_msg, "warning")
                    except Exception:
                        pass
                    time.sleep(backoff_minutes * 60)
                    consecutive_errors = 0  # Reset after backoff

            time.sleep(30)
    except KeyboardInterrupt:
        pass

    # Clean shutdown
    log_action("scheduler", "daemon_stopped", details="Graceful shutdown")
    log.info("Daemon stopped gracefully")
    console.print("\n[yellow]Daemon stopped.[/yellow]")
    try:
        from trading.monitor.notifications import notify
        _notify_safe(notify, "Daemon Stopped", "Trading daemon stopped gracefully", "warning")
    except Exception:
        pass
